### ISSUE TITLE
Infinite restart loop and eventual crash when hwinfo64 is starting up and scanning GPU sensors.

### ISSUE THREAD

**Issue by ssateneth** [luke-jr/bfgminer#110]
Basically the title. On Win7 x64, I wanted to see what my VRM temperatures were like on my 5970's and started hwinfo64 4.03-1715 while bfgminer 2.7.1 was running. While it was scanning, bfgminer when into an infinite restart loop. I couldn't catch the details fast enough because bfgminer was scrolling really fast, but I think I saw that it wasn't able to pick up fan speed from a GPU.

**Comment by luke-jr** [comment]
Try:

```
bfgminer *your options HERE* --no-restart --debuglog 2>bfgminer.log
```

**Comment by ssateneth** [comment]
Log: https://dl.dropbox.com/u/9768004/bfgminer.log
Picture after hwinfo64 is done detecting: https://dl.dropbox.com/u/9768004/bfgminer.png

**Comment by luke-jr** [comment]
So... it worked fine that time? or?

**Comment by ssateneth** [comment]
No. That was the same crash as before.

**Comment by luke-jr** [comment]
How did you get a screenshot if it was crashed? O.o;;

**Comment by ssateneth** [comment]
Maybe I'm using the wrong words. When I say "crash", I mean it simply refuses to mine. The card shows as "off" after I hit enter and it completes starting up.

**Comment by luke-jr** [comment]
I don't see any sign that the screenshot isn't working, or that the debug.log had any devices stop mining :/

**Comment by ssateneth** [comment]
Bah, sorry, I got mixed up with issues. I thought we we're talking about the atomic_add problem, but we solved that last night. Ignore everything I said from "No. That was the same crash as before." onward.

With this...
bfgminer _your options HERE_ --no-restart --debuglog 2>bfgminer.log
... it continued to mine, but every other card failed to have a fan speed oddly.

**Comment by luke-jr** [comment]
Sounds like an ADL quirk. Can you post that debug.log to confirm?

**Comment by ssateneth** [comment]
I already posted the debug log after you told me to run bfgminer _your options HERE_ --no-restart --debuglog 2>bfgminer.log
https://dl.dropbox.com/u/9768004/bfgminer.log

Look for "stopped reporting fanspeed due to driver corruption"
BTW the same exact thing just happened on 2.6.6

**Comment by luke-jr** [comment]
So... with --no-restart, it works but just breaks fan speed?

**Comment by luke-jr** [comment]
Reverting ADL restart in e0ad72e; it should survive whatever glitches this does now (please close this bug when you confirm with 2.7.5)

**Comment by ssateneth** [comment]
started hwinfo, 5970's lost fan speed as hwinfo was scanning GPU's, eventually caused all 5970 to lose fan speed, but when hwinfo finished scanning, all my 5970's magically got fan speed back. also bfgminer never restarted, so looks like its fixed
