### ISSUE TITLE
Not able to update memory clock or GPU clock from BFG miner, clock speed keeps getting reset.

### ISSUE THREAD

**Issue by tortib** [luke-jr/bfgminer#126]
I have two GPUs one is set at 950Mhz the other is set at 600MHz I can use BFGMiner to change the clock speed on my first card to whatever i please.  Changing the clock speed on the 2nd card is impossible, it doesn't respond to any values I set even for the memory clock speed.  The BIOS on both cards (cards are made by same manufacturer) are set to 950 so I should be able to set it to 950 as I please.  When I first boot the windows 7 machine up it works for a while (950MHz) and then sets itself to 600MHz automatically, the other 5850 stays at the correct clock speed (950MHz) and allows me to change the memory clock and the GPU clock speed from within bfgminer.
System Specs:
Windows 7 64bit
ATI Radeon HD 5850 stock BIOS set to 950MHz
Working GPU: also Radeon 5850
I have tried both BFGMINER 2.7.5 and CGMINER 2.7.5
BFGMINER Log File http://pastebin.com/2bTnmRcc
Command: bfgminer --gpu-threads 3 -u 1AjsBbH9BEJW89vkpYhJYCwq5YDWWSLVw6 -p password -o http://ra.mining.eligius.st:8337
BFGMINER config file: http://pastebin.com/Q4hE47ns

UPDATE:  I was able to change the clock speed to 950MHz on the card that keeps getting set to 600MHz, however once it's set to 950MHz it resets to 600MHz.

**Comment by luke-jr** [comment]
Your GPU seems to be getting hot - up to 81 C when the clocks are changed. Try increasing --temp-target and/or --temp-overheat (but beware of the dangers of damaging the card more!)?

**Comment by tortib** [comment]
The card that is running at 950MHz runs at 81C the one that is clocked at 600MHz runs at 93.5C.  I don't think adjusting that argument would make a difference?  What values should I use?

**Comment by tortib** [comment]
I set --temp-target to 100 and it still lowers the clock speed to 600MHz when It's set to 950MHz

**Comment by luke-jr** [comment]
Note: @tortib 's GPU fan had died.
