### ISSUE TITLE
Pool Priority commandline/config, and TUI

### ISSUE THREAD

**Issue by purelithium** [luke-jr/bfgminer#130]
Currently, if a user has multiple pools entered in the config file,  the miner uses that order as the pool priority. This requires a full miner restart and time/hashes lost. The user should be able to modify this priority list through the [P]ool Management selection. This modification should then persist through shutdown and restart if the user writes the changes to the config file through the [S]ettings selection.

**Comment by jaketri** [comment]
If pool management code is touched then it would be nice to be able to save/restore from/to config file the pool state (enable/disable).

**Comment by luke-jr** [comment]
@jaketri That sounds like a slightly more in-depth change, but really should be in another issue of its own.

**Comment by jaketri** [comment]
@luke-jr OK no problem ... I'll open a separate issue for it ... I was thinking it is manage by same code ...

**Comment by luke-jr** [comment]
@blinkier implemented this
