### ISSUE TITLE
OpenCL: High CPU usage at higher/lower intensities

### ISSUE THREAD

**Issue by senseless** [luke-jr/bfgminer#131]
When running at low intensities the miner consumes an inordinate amount of cpu.

Setup: Running 3x 5830 on a dual core AMD AM3+ on windows 7 using BFGMiner 2.7.5. I remote into the machine as it's not at my house. So VNC uses 10-20% cpu when I'm connected. I'm using phatk kernel. However, I also tested pocblm and it's occurring there as well. 

If I set my cards to intensity 0 the cpu usage is  75% (spanning both cores)
If I set my cards to intensity 1 the cpu usage is  60% 
If I set my cards to intensity 2 the cpu usage is  45% 
If I set my cards to intensity 3 the cpu usage is  25% 
If I set my cards to intensity 4 the cpu usage is  12% 
If I set my cards to intensity 5 the cpu usage is  4% 
If I set my cards to intensity 6-9 the cpu usage is  0% 
If I set my cards to intensity 10+ the cpu usage is  100% 

It does not matter what the other settings in my configuration are. I've tried setting a configuration solely with intensity and the pool (no other settings (everything default)) and the problem still occurred.

It's important for people who need to use their computers while mining to have a low intensity for best desktop performance. I'm sure not everyone has dedicated mining rigs.

**Comment by purelithium** [comment]
I notice this as well.

BFGMiner 2.8.0 on 6870&7770 diablo & diakcgn respectively. Intensity set at 14 = CPU %50 usage by the process. Windows 7 64bit.

**Comment by subSTRATA** [comment]
It's up to driver - OpenCL implementation - not miner. Check on Internet, there are many nice articles about the issue.
