### ISSUE TITLE
CUDA driver

### ISSUE THREAD

**Issue by senseless** [luke-jr/bfgminer#132]
The 100% cpu usage on one core problem also occurs with Nvidia users using the opencl kernels. I would like to see a cuda driver added to bfgminer.

Willing to offer a reward for completion of a working cuda kernel that interfaces with bfgminer.

**Comment by yhaenggi** [comment]
somany ppls needing cuda kernels and yet there is nothing usefull around :S

**Comment by xavier83** [comment]
I need cuda kernels too.
