### ISSUE TITLE
Hardware errors reported in versions 2.7.1 through 2.8.0 (Dynamic Intensity)

### ISSUE THREAD

**Issue by wizkid057** [luke-jr/bfgminer#143]
Testing on my hardware I noticed that I was getting hardware errors with versions 2.7.1 through 2.8.0.

I've confirmed that versions prior to 2.7.1 do not appear to have this issue, which would also confirm that the issue is not actually related to my hardware.

Test platform: Win32, Radeon HD 6990 x 2
Test criteria: 5000 accepted shares, count hardware errors.

**Comment by wizkid057** [comment]
Going to close this until I can reconfirm these issues.

**Comment by wizkid057** [comment]
After retesting, it seems that all versions 2.7.1 through 2.8.0 produce a low, but seemingly random amount of HW errors.  2.7.0 and prior versions I'm not able to get any HW errors.  I will continue to run on 2.7.0 to verify, however I've passed 5000 shares without issue so far.  It only took 34 shares in my last run of 2.7.1 to produce a HW error however.

**Comment by wizkid057** [comment]
Just an update: Ran 2.7.0 for > 30k shares without issue.

**Comment by wizkid057** [comment]
This issue seems to stem from commit e8984067da23cb2a62a3e313ab84e401e079443d , changes to the dynamic GPU intensity code.  Using a static intensity yields no hardware errors.

**Comment by purelithium** [comment]
I see this issue as well. Causes BSOD in Windows 7 64bit

**Comment by luke-jr** [comment]
@purelithium This bug has nothing to do with BSODs.

**Comment by purelithium** [comment]
@luke-jr Yes, I realize this now, it turned out the BSOD was a heat issue with my CPU, it's been fixed since.

**Comment by luke-jr** [comment]
Fixed (by Con) in 1c22c0e / d03a622
