### ISSUE TITLE
Official pdcurses 3.4 DLL is flagged by antivirus

### ISSUE THREAD

**Issue by luke-jr** [luke-jr/bfgminer#149]
["burger" reports self-compiled dll is fine](https://bitcointalk.org/index.php?topic=78192.msg1207886#msg1207886)

**Comment by burger2** [comment]
I'm burger on the forums... and I can also confirm that when I downloaded http://voxel.dl.sourceforge.net/project/pdcurses/pdcurses/3.4/pdc34dllw.zip and scanned it with AVG it didn't find any virus.

https://bitcointalk.org/index.php?topic=78192.msg1208826#msg1208826

**Comment by luke-jr** [comment]
New BFGMiner builds will now use a self-compiled pdcurses DLL, which has been checked against virus scanners cleanly.

**Comment by burger2** [comment]
Sounds very good!
