### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by Mhorbid** [luke-jr/bfgminer#158]
BFGMiner fails to build under cygwin.

make output:
http://pastebin.com/syzNyKgW

cpp -dM:
http://pastebin.com/xZYi9e19

**Comment by luke-jr** [comment]
Is OpenCL/ADL available for testing somehow?

**Comment by luke-jr** [comment]
Compile and CPU mining tested with 26459c5

**Comment by Mhorbid** [comment]
Compiles fine without the libusb1.0-devel package, but throws the above error with it.
Seems like that's the issue.
