### ISSUE TITLE
Garbled text when connected to eligius pool with 2.8.1

### ISSUE THREAD

**Issue by mrvdb** [luke-jr/bfgminer#159]
The 'Accepted ....' lines contain garbled text when I connect bfgminer to eligius. This happens only when connected to eligius and not to other pools (at least the ones I am using)

Screenshot here: http://flic.kr/p/df4p71

$ uname -a
Linux mrb 3.3.7-999-optimus #201206010200 SMP PREEMPT Fri Jun 1 02:55:51 EEST 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mrvdb** [comment]
Using --no-gbt on the command line makes the garbled text disappear.

**Comment by luke-jr** [comment]
Fixed with 3b093c6
