### ISSUE TITLE
Shares that would solve block become lost instead

### ISSUE THREAD

**Issue by subSTRATA** [luke-jr/bfgminer#184]
When solo-mining Terracoins using BFGMiner 2.9.3 or CGMiner 2.9.4, it happened on way too many occassions that "best share" value was higher than Terracoin network difficulty but neither was share accepted, nor rejected, nor some other message was posted on screen. It happened in both pure solo mode (just local Terracoin server as pool 0, no other pools @ bfgminer.conf) and in load-balance, rotate and failover modes (failover-only was "true" at all times). Not sure about submit-stale and no-submit-stale, I tend to switch inbetween those two quite often.

Version 2.8.3 seems to not have mentioned problem, but I can not be sure because there is no "best share" value shown on TUI and, as mentioned above, once issue happens there is no message of any kind shown on screen.

**Comment by luke-jr** [comment]
Need more details. getwork or GBT? Do you have a debug log when it happened? Please also provide a getwork or getblocktemplate from your solo terracoin server.

**Comment by luke-jr** [comment]
Also, does terracoin do anything unusual with deciding what is a valid block?

**Comment by luke-jr** [comment]
Reported fixed: https://bitcointalk.org/index.php?topic=78192.msg1403363#msg1403363
