### ISSUE TITLE
At seemingly random times, intensity changes following specific pattern

### ISSUE THREAD

**Issue by subSTRATA** [luke-jr/bfgminer#185]
For over a month now, using different versions of both BFGMiner and CGMiner on WinXP SP3 machine with various Catalyst versions installed (10.4 - 11.12) and two different GPUs (4670 and than 5770), the following situation happens regardless of initial intensity setting:
1. Hash rate varies very little most of the time but than
2. it drops considerably
3. just to be rised to noticably higher value than using initial intensity and than
4. it slowly goes back to value at step 1.

In numbers - values for (5s) field:
1. 200 Mhash
2. 70 Mhash
3. 280 Mhash
4. 280 > 200 Mhash

Even though I was looking at debug data (a lot), I was unable to find any specific event that triggers the issue. It's really nasty issue because user can end up with ruined GPU - or worse - if he uses high initial intensity setting. Unless auto-gpu and / or auto-fan options are used (and properly set), user must count with inevitable GPU usage rise and set initial intensity to much lower value than he could set otherwise, which results in lower average hash rate. If mentioned options are used, speeds tend to be adjusted almost constantly and in abrupt fashion.

It's not just my system affected - I've seen many videos, screenshots and posts where hash rate behaved the same way as explained above.

For example, check (5s) values here: https://bitcointalk.org/index.php?topic=54673.msg1363120#msg1363120

**Comment by luke-jr** [comment]
Sounds like just the 5s average is hitting edges of sampling, not actual variation in hashing. Even if there is variation, this is (assuming not dynamic-intensity-mode) a driver/card issue, and there's nothing we can do about it. Closing.
