### ISSUE TITLE
Do not perform get_transactions (stratum) every time

### ISSUE THREAD

**Issue by slush0** [luke-jr/bfgminer#186]
In current implementation, bfgminer's stratum implementation calls mining.get_transactions() for every received job. There's really no reason to do this and hundreds of miners asking for complete list of transactions are just wasting server's resources.

Please consider to implement checking for only some jobs. There's practically no chance how to abuse hashpower by the poolop even if miner checks tenth job or even less.

**Comment by luke-jr** [comment]
Implemented in 2708f34

**Comment by slush0** [comment]
Hm, this really didn't help, as it is just optional argument and default behaviour is "fuck up pool as much as possible" :-/.

This is exactly the reason why other pool ops fear to implement get_transactions to their pools. With so aggressive policy, you're only increasing pool traffic. By making this less abusive, maybe others will implement it.

**Comment by luke-jr** [comment]
Sending transactions shouldn't mess up the pool period. That's just a sign of a poorly run pool.

**Comment by slush0** [comment]
You didn't sleep well today, right? Please be constructive.

Sending transactions for every job broadcast is absolute overkill, and it sends memory pool N times every 30 seconds (where N is amount of connected bfgminers).

Please do your checks in less invasive way, otherwise there won't be any pool providing such API. If you're not going to modify default behaviour, I'll disable get_transaction on my pool as well. Currently ~20 bfgminers are doing higher pool load than the rest of 2000 connected miners.
