### ISSUE TITLE
--coinbase-sig does not append 

### ISSUE THREAD

**Issue by jborkl** [luke-jr/bfgminer#187]
Bitcoin-qt or bitcoind, version 0.7.1, or either next test.

--coinbase-addr will start properly and add gbt

--coinbase-sig gives a error that it will not append at all.

<jborkl>  [2012-12-03 13:14:23] Probing for an alive pool
<jborkl>  [2012-12-03 13:14:23] Cannot append coinbase signature at all on pool 42949
<jborkl> 5 (0)
<jborkl>  [2012-12-03 13:14:23] No suitable long-poll found for pool http://localhost
<jborkl> 2
<jborkl>  [2012-12-03 13:14:23] MMQ 0.0: Frequency set to 200 Mhz (range: 2-210)
<jborkl>  [2012-12-03 13:14:23] MMQ 0.3: Frequency set to 200 Mhz (range: 2-210)
<jborkl>  [2012-12-03 13:14:23] MMQ 0.1: Frequency set to 200 Mhz (range: 2-210)
<jborkl>  [2012-12-03 13:14:23] MMQ 0.2: Frequency set to 200 Mhz (range: 2-210)

Windows 7 64, any version of bfgminer that had --coinbase enabled

**Comment by luke-jr** [comment]
Fixed in libblkmaker: b5ab89e
