### ISSUE TITLE
cpu miner uses all threads to the max, even if there is no hashing being performed

### ISSUE THREAD

**Issue by leaf-node** [luke-jr/bfgminer#210]
i've noticed that all cpu threads are shown to be maximally used, according to various system monitors such as htop, even if some or all are listed as performing 0 Mh/s.

maybe there is some benefit from not sleeping any threads for even a bit at a time, but it's probably not good for the electric bill, or for the temperature of the computer.

i'm running Debian GNU/Linux on a laptop with a core i3 390M.

**Comment by GilesBathgate** [comment]
All CPU's are being used maximally all the time. The device statistics are based on the number of accepted shares, and as such are only a guide/estimate. Even when it says 0 Mh/s its really running flat out. 

P.S you can close this issue now.

**Comment by luke-jr** [comment]
I'm confused. You were CPU mining?

**Comment by leaf-node** [comment]
yes, i was, to test out the software.
