### ISSUE TITLE
configure error for openwrt backfire cross-compile

### ISSUE THREAD

**Issue by dony71** [luke-jr/bfgminer#218]
when i run :
./configure --prefix=$TOOLCHAIN_DIR --host=mips-openwrt-linux-uclibc --

it gives error :

=== configuring in libblkmaker (/home/user/openwrt/bfgminer/libblkmaker)
configure: running /bin/bash ./configure --disable-option-checking '--prefix='  '--host=mips-openwrt-linux-uclibc' '--' 'host_alias=mips-openwrt-linux-uclibc' --cache-file=/dev/null --srcdir=.
configure: error: invalid variable name: `--cache-file'
configure: error: ./configure failed for libblkmaker

**Comment by luke-jr** [comment]
Got it figured out?
