### ISSUE TITLE
dyld: Library not loaded: /usr/local/lib/libblkmaker_jansson-0.1.0.dylib

### ISSUE THREAD

**Issue by njdro** [luke-jr/bfgminer#220]
Any clue how to aquire this file for OSX 10.8?  After all the hoop jumping, i managed to compile, but now this... and can't even find a source for it.  'brew install jansson' does not provide.  Thanks!

**Comment by luke-jr** [comment]
Check under bfgminer/libblkmaker/.libs dir

**Comment by njdro** [comment]
./configure --enable-scrypt 'PKG_CONFIG_PATH=/Users/ster/coin/bfgminer/libblkmaker/.libs:/usr/local/Cellar/curl/7.29.0/lib/:/usr/local/opt/curl/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/mountain_lion:/usr/local/lib'
[...........]
Making all in libblkmaker
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DPACKAGE_NAME=\"libblkmaker\" -DPACKAGE_TARNAME=\"libblkmaker\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"libblkmaker\ 0.1\" -DPACKAGE_BUGREPORT=\"luke_libblkmaker@dashjr.org\" -DPACKAGE_URL=\"http://gitorious.org/bitcoin/libblkmaker\" -DPACKAGE=\"libblkmaker\" -DVERSION=\"0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.    -I/usr/local/Cellar/jansson/2.4/include  -g -O2 -MT libblkmaker_jansson_0.1_la-blkmaker_jansson.lo -MD -MP -MF .deps/libblkmaker_jansson_0.1_la-blkmaker_jansson.Tpo -c -o libblkmaker_jansson_0.1_la-blkmaker_jansson.lo `test -f 'blkmaker_jansson.c' || echo './'`blkmaker_jansson.c
libtool: compile:  gcc -std=gnu99 -DPACKAGE_NAME=\"libblkmaker\" -DPACKAGE_TARNAME=\"libblkmaker\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"libblkmaker 0.1\"" -DPACKAGE_BUGREPORT=\"luke_libblkmaker@dashjr.org\" -DPACKAGE_URL=\"http://gitorious.org/bitcoin/libblkmaker\" -DPACKAGE=\"libblkmaker\" -DVERSION=\"0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I/usr/local/Cellar/jansson/2.4/include -g -O2 -MT libblkmaker_jansson_0.1_la-blkmaker_jansson.lo -MD -MP -MF .deps/libblkmaker_jansson_0.1_la-blkmaker_jansson.Tpo -c blkmaker_jansson.c  -fno-common -DPIC -o .libs/libblkmaker_jansson_0.1_la-blkmaker_jansson.o
mv -f .deps/libblkmaker_jansson_0.1_la-blkmaker_jansson.Tpo .deps/libblkmaker_jansson_0.1_la-blkmaker_jansson.Plo
/bin/sh ./libtool  --tag=CC   --mode=link gcc -std=gnu99 -I/usr/local/Cellar/jansson/2.4/include  -g -O2 -L.libs -lblkmaker-0.1 -L/usr/local/Cellar/jansson/2.4/lib -ljansson  -no-undefined -version-info 4:0:4  -o libblkmaker_jansson-0.1.la -rpath /usr/local/lib libblkmaker_jansson_0.1_la-blkmaker_jansson.lo  
libtool: link: rm -fr  .libs/libblkmaker_jansson-0.1.0.dylib .libs/libblkmaker_jansson-0.1.dylib .libs/libblkmaker_jansson-0.1.la .libs/libblkmaker_jansson-0.1.lai
libtool: link: gcc -std=gnu99 -dynamiclib  -o .libs/libblkmaker_jansson-0.1.0.dylib  .libs/libblkmaker_jansson_0.1_la-blkmaker_jansson.o   -L.libs /Users/ster/coin/bfgminer/libblkmaker/.libs/libblkmaker-0.1.dylib -L/usr/local/Cellar/jansson/2.4/lib -ljansson  -O2   -install_name  /usr/local/lib/libblkmaker_jansson-0.1.0.dylib -compatibility_version 5 -current_version 5.0 -Wl,-single_module
libtool: link: (cd ".libs" && rm -f "libblkmaker_jansson-0.1.dylib" && ln -s "libblkmaker_jansson-0.1.0.dylib" "libblkmaker_jansson-0.1.dylib")
libtool: link: ( cd ".libs" && rm -f "libblkmaker_jansson-0.1.la" && ln -s "../libblkmaker_jansson-0.1.la" "libblkmaker_jansson-0.1.la" )
[...........]

make

cp libblkmaker-0.1.0.dylib /usr/local/lib/

./bfgminer -o http://blah.blah.com:8332 -u blah -p blah
dyld: Library not loaded: /usr/local/lib/libblkmaker_jansson-0.1.0.dylib
  Referenced from: /Users/ster/coin/bfgminer/./bfgminer
  Reason: image not found
Trace/BPT trap: 5

???

**Comment by luke-jr** [comment]
Did you get the one in the .libs dir, or the fake text file?

**Comment by njdro** [comment]
i'm not sure i knew the difference...
so i re-tried: 
sudo cp /Users/ster/coin/bfgminer/libblkmaker/.libs/libblkmaker_jansson-0.1.0.dylib /usr/local/lib/

and it seems to work.... i suppose i needed a little hand-holding...
thank you! now to find a pool that doesn't fail connects.

**Comment by TrooperT** [comment]
check a look at http://github.com/nwoolls/homebrew-cryptocoin

its an all in one brew formula you can use to pull down the latest bfgminer with the brew install [FORMULA] --HEAD

**Comment by njdro** [comment]
nwoolls homebrew and binaries work.
this can be closed.
