### ISSUE TITLE
Trace/BPT trap: 5

### ISSUE THREAD

**Issue by njdro** [luke-jr/bfgminer#221]
--debug 

Probing for an alive pool
Testing pool http://bitcoinpool.com:8334/
Popping work to stage thread
HTTP request failed: The requested URL returned error: 400 Bad Request
Failed to connect in json_rpc_call
X-Roll-Ntime expiry set to 60
Calculating midstate locally
Successfully retrieved and deciphered work from pool 0 http://bitcoinpool.com:8334/
Pushing pooltest work to base pool
New block: ...fd4b3ff742cd7105 diff 7.67M
Pushing work to getwork queue (queued=N)
Long-polling activated for http://bitcoinpool.com:8334/listenChannel (getwork)Trace/BPT trap: 5

getting trap 5 for all my pools.

searching reports that it's about the DYLD_LIBRARY_PATH, but i don't know how to correct.  --correct it prior configure or prior execution, and where should path point to?

OSX 10.8.3  / dependencies via Brew

**Comment by fabulouspanda** [comment]
This is probably one of the dependencies missing, although unless it's one of the more obvious ones it can be tricky to solve. If you open the bfgminer binary in textedit you'll be able to see near the top a bunch of library locations it's relying on loading so the first port of call would be to verify that they're all there… if so, either uninstall and reinstall them or start worrying about dependencies… you might have more luck specifically linking the libraries at the ./configure stage a la PKG_CONFIG_PATH=/usr/local/opt/curl/lib/pkgconfig

**Comment by njdro** [comment]
i'm honestly trying my best. 
my libs exist as per your suggestion: http://pastebin.com/Jv1rjMzN
debug output: http://pastebin.com/3RkgMUim

**Comment by fabulouspanda** [comment]
So presumable the
./configure <options>
make
(sudo) make install
runs without errors? I don't really know what's wrong with it but this comes up with a quick google search, though it's possible just ltc related:

export GPU_MAX_ALLOC_PERCENT=100

export GPU_USE_SYNC_OBJECTS=1

export DISPLAY=:0

**Comment by njdro** [comment]
config/make no errors.
exports result in nothing different.
http://pastebin.com/agFgXjte

only issues with OSX, not linux.

... just found those export instructions, they seem to be for linux opencl & litecoin.

**Comment by fabulouspanda** [comment]
I never have to use  CFLAGS="-O2 -msse2" compiling bfgminer on OS X maybe try without that
I also only use the pkg-config for curl/jansson as listed on the readme.

If you're totally stuck you might try MacMiner https://bitcointalk.org/index.php?topic=197110.0

10.8 version has bfgminer included check the view menu
10.7 has cgminer included

if you want command line you can 
cd /Applications/MacMiner.app/Contents/Resources/bfgminer/bin
./bfgminer <pool, user, password, options as normal)

and something vaguely similar for cgminer on 10.7 but show package contents on the app to get the precise file path for the cgminer binary

**Comment by njdro** [comment]
Thanks for the added info including MacMiner. 
i ran from /Applications/MacMiner.app/Contents/Resources/bfgminer/bin with the exact same result, so it's my setup at fault -- at least i know "something" now.
I've been using Diablo+Proxy and wanted to replace it with bfgminer; guess i'm SOL.

**Comment by njdro** [comment]
nwoolls homebrew and binaries work. (https://github.com/nwoolls/homebrew-cryptocoin)
this can be closed.
