### ISSUE TITLE
Unknown stratum msg

### ISSUE THREAD

**Issue by fabulouspanda** [luke-jr/bfgminer#225]
I've got bfgminer running fine, but it keeps outputting:

Stratum from pool 0 requested work update
 [2013-05-01 01:18:44] Unknown stratum msg: {"error": [-3, "Method 'get_transactions' not found for service 'mining'", null], "id": "txlistfc8", "result": null}

Is this something to do with getwork perhaps, or something I should be concerned about?

**Comment by luke-jr** [comment]
It means your pool only supports blind stratum (bad for bitcoin). It shouldn't show without --debug...

**Comment by fabulouspanda** [comment]
ah, thanks - i'm using -q but without the TUI, maybe that's why it's showing up? also, using slush's pool

**Comment by sradforth** [comment]
I'm seeing this message too with www.btcpoolman.com.  When you say blind stratum is bad for bitcoin is it something the pool operator needs fix this and/or does it adversely affect anyone mining in that pool?

**Comment by luke-jr** [comment]
It adversely affects people using Bitcoin; worse the larger the pool is.

**Comment by daryltucker** [comment]
https://github.com/slush0/stratum/issues/21
https://github.com/luke-jr/bfgminer/issues/186
