### ISSUE TITLE
disable-bitforce

### ISSUE THREAD

**Issue by alphaonex86** [luke-jr/bfgminer#241]
With under linux:
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --libdir=/usr/lib64 --disable-dependency-tracking --docdir=/usr/share/doc/bfgminer-3.1.0 --disable-adl --disable-avalon --disable-bitforce --enable-cpumining --disable-icarus --disable-modminer --with-curses --enable-opencl --enable-scrypt --with-system-libblkmaker --with-libudev --without-sensors --disable-x6500 --disable-ztex
I have:
bfgminer-ocl.o: In function `file_contents':
/var/tmp-disk/portage/net-misc/bfgminer-3.1.0/work/bfgminer-3.1.0/ocl.c:229: undefined reference to`open_bitstream'
Fixed with: --enable-bitforce

Cheer,

**Comment by luke-jr** [comment]
Already fixed in git.
