### ISSUE TITLE
--temp-cutoff disables incorrect GPU, does not prevent overheat.

### ISSUE THREAD

**Issue by Farthom** [luke-jr/bfgminer#244]
I'm experiencing issues with the --temp-cutoff parameter, when the feature activates, it appears to disable the wrong GPU, and thus does not prevent the GPU from overheating. I have attached a screenshot, "OCL 2" is the overheating core, (I set the overheat to 95)  but the drop in temperature on "OCL 1" indicates the wrong GPU has been throttled, meanwhile the temp on "OCL 2" continues to rise. 

This issue also occurs on cgminer, and I thus I believe it was originally introduced in cgminer. There seems to be some internal mismatch between device and threads.... 

![screen](https://f.cloud.github.com/assets/4826945/706802/57866486-ddfc-11e2-947a-ce4b27646b91.jpg)

**Comment by luke-jr** [comment]
Do you have the GPU mapping configured correctly? (see README.GPU)

**Comment by Farthom** [comment]
I was not aware of these options... I ran bfgminer with the -n option and there are no extra displays or cards, and both systems seem to report 4 GPUs. Of course that doesn't mean the orders are the same! The system is a dual 7990, thus all cards read the same, I'll need some way to determine what maps to what. Any ideas?

**Comment by luke-jr** [comment]
Try using the GPU Management menu to disable them and enable one at a time, and correlate the temperatures.

**Comment by Farthom** [comment]
Perfect! I discovered the same mismatch by performing the above. It turns out I need to swap the middle two GPUs. I have solved the problem with --gpu-map 1:2,2:1

Thank you so much luke-jr for your prompt and useful replies!
