### ISSUE TITLE
FYI: innocuous race condition in poclbm kernel (perhaps others)

### ISSUE THREAD

**Issue by craiig** [luke-jr/bfgminer#252]
Apologies if you've already come across this or it's covered in a thread I can't find.

poclbm130302.cl contains the line:

```
#define SETFOUND(Xnonce) output[output[FOUND]++] = Xnonce
```

In the _extremely_ unlikely event that two concurrent work items find a nonce that works, the non-atomic increment to output[FOUND] will happen simultaneously and both work items will use the same incremented value to write into the same location of output. 

Writes to the same location are typically undefined and sometimes results in corrupted data, so this may be worth fixing. However, this doesn't seem to be an issue on my machine and probably isn't an issue on others. On my Macbook Pro w/ 330M the result written to output is not corrupted and is just the nonce from the highest id work-item. I.e. if work-items with global-id 0 and 1 find a nonce, then the write from 1 will succeed.

If there is no data corruption possible on any machine, and since you're probably only interested in finding a single nonce that works, then this is a total non-issue. It's probably not even worth improving the way a found nonce is written considering it happens so rarely, but if you accept you only want a single nonce (even if multiple are found), you may be able to improve the output logic slightly.

Just thought someone out there might find it interesting.

**Comment by luke-jr** [comment]
This was a conscious decision due to atomic increments having two problems:
- They don't work with older OpenCL SDKs, such as the Catalyst performing best on 5xxx cards
- They made GPU mining more unreliable with underclocked memory.

Plus the fact that it's rare enough that nobody's ever (to my knowledge) encountered a problem.

**Comment by craiig** [comment]
Makes sense! Thanks for the response. :)
