### ISSUE TITLE
x6500 going sick and dead in 5 minutes or less

### ISSUE THREAD

**Issue by vpereira** [luke-jr/bfgminer#257]
Im trying to run a x6500 rev c with bfgminer, and it goes offline. the backtrace running with -D gives me no clue any idea?

im starting it with -S x6500:auto or -S /dev/ttyUSB02.. it works for 10 minutes and then it is marked as SICK and DEAD. temperature is around 40 degrees.. it has a heatsink and fan. any idea how to debug it?

**Comment by luke-jr** [comment]
If you add -DDEBUG_JTAG_CLOCK to your CFLAGS, it will debug-log a lot more detail.

**Comment by vpereira** [comment]
ok I started a discussion at https://bitcointalk.org/index.php?topic=168174.new#new.

**Comment by vpereira** [comment]
looks like the problem was a usb hub, that is working, but I believe that the x6500 + fan pull more current from usb as it was available..
