### ISSUE TITLE
ICA 0: Failed to reopen on /dev/ttyUSB0

### ISSUE THREAD

**Issue by stefan-11** [luke-jr/bfgminer#258]
When using 8 Block Erupter USBs (with Ubuntu 12.10) all the USBs fail after a few seconds.

BFGMiner was started as follows:
./bfgminer -o stratum+tcp://stratum.btcguild.com:3333 -u stefan311_minerone -p 123 -S /dev/ttyUSB0 -S /dev/ttyUSB1 -S /dev/ttyUSB2 -S /dev/ttyUSB3 -S /dev/ttyUSB4 -S /dev/ttyUSB5 -S /dev/ttyUSB6 -S /dev/ttyUSB7 --icarus-options 115200:1:1 --icarus-timing 3.0=100 -queue 10 -D -T --verbose 2>>/var/www/bfgminer-logs/bfgminer-log.txt

Please find the log here:
https://dl.dropboxusercontent.com/u/31515585/failed-bfgminer-log.txt

**Comment by luke-jr** [comment]
Usually this is a power issue.

**Comment by stefan-11** [comment]
Thank you. Seems as if the USB Hub was the issue (2 Anker 7-Port). I now switched to two d-link hubs and everything works fine.
