### ISSUE TITLE
Block time is not displayed correctly

### ISSUE THREAD

**Issue by gades** [luke-jr/bfgminer#261]
block time is not displayed correctly
![started](https://f.cloud.github.com/assets/4200730/901602/f3e41456-fb82-11e2-9466-f3dd4acac179.png)

**Comment by luke-jr** [comment]
Please elaborate.

**Comment by gades** [comment]
Time unit found not correspond to reality. Look at the date and time the application starts its operation, as well as the date found block. Previously, this parameter displays the time when he found a new unit in the network.

2 àâã. 2013, â 22:05, Luke-Jr notifications@github.com íàïèñàë(à):

**Comment by luke-jr** [comment]
I see what you mean, looking into it..

**Comment by gades** [comment]
![block](https://f.cloud.github.com/assets/4200730/903776/89c85240-fbb3-11e2-8ee0-f03f572ceb97.png)

**Comment by luke-jr** [comment]
Fixed in 37e0753, thanks.
