### ISSUE TITLE
make error on debian wheezy 32bit (from git)

### ISSUE THREAD

**Issue by njdro** [luke-jr/bfgminer#266]
[...]
bfgminer-miner.o: In function `main':
/home/user/bfgminer/miner.c:9863: undefined reference to`httpsrv_port'
/home/user/bfgminer/miner.c:9866: undefined reference to `httpsrv_port'
collect2: error: ld returned 1 exit status
make[2]: *** [bfgminer] Error 1
make[2]: Leaving directory`/home/user/bfgminer'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/home/user/bfgminer'
make: **\* [all] Error 2

bfgminer from git clone

debian wheezy 32bit.  This did not error on a debian testing 64bit.  not sure the difference. ./configure shows good config.

no make errors 4 or 5 days ago on same machine before git pull.

**Comment by luke-jr** [comment]
It's only 3.1.4 if you get the 3.1.4 tag or download. You're trying to build the bleeding edge here.
I will look into this bug more.

**Comment by luke-jr** [comment]
Fixed with e8ac71f
