### ISSUE TITLE
When secondary pool longpolls a new block first with --failover-only, BFGMiner idles and floods the primary pool with requests until it has caught up

### ISSUE THREAD

**Issue by luke-jr** [luke-jr/bfgminer#28]

**Comment by luke-jr** [comment]
Fixed in f401e76d715aa75dda2e1d03e18aa5562b430ffc

**Comment by add1ct3dd** [comment]
Is this definitely fixed? I'm getting this issue right now on the latest 3.1.0!

**Comment by luke-jr** [comment]
@add1ct3dd Are you sure it's the same issue? The flooding in this case was to the pool and transparent to the user..

**Comment by Squeezle42** [comment]
Luke-Jr - I have been working on (started poolerd, migrated to cpuminer - but have found some ways to make it better (I get around 4x as many proofs accepted over the same amount of time with bfgminer) I've tested this on BTCguild, 50BTC, bitminter, deepbit, and solo mining) it is related mostly to looking at the right places for proof based on depth into the new blocks and succeeds (keeping failed success to retry for success later) , but is held up by lack of stratum support, I'm trying to figure out how to integrate this as part of the SHA256d but very much improved, I think given work this can be scaled to asic and of course everything under, but the project seems to be spreading so I could use some help on merging. Should I go poolerd route or further with BFG?

PS(It's sloppy and not worth sharing until I figure out which direction to run with it, but works in every test so far)

**Comment by luke-jr** [comment]
@Squeezle42 I'm not sure what you mean entirely, but patches are certainly welcome to improve things in BFGMiner.

**Comment by Squeezle42** [comment]
Sorry about the vegaraties, experiencing a flood in my area, but what I
mean is I am getting 4x the accepted proofs with my miner, and I would like
to figure out how to add that efficancy to BFG so I can start learning the
stratum protocol, but I keep having issues of network availability for
bandwidth from most pools upon certain numbers (eg, only so many accepted
per pool per hour) after which there seems to be no use sending proof, so i
would like to add or change to linked lists, the pools so far seem to limit
once I get to efficiency (actual numbers being around 3.5mega hashes per
proof (effctive) providing 4 per thread per hour.  But processing of proof
pool side is lacking compared to solo, even with 1M hash servers(Norway is
oddly best)

**Comment by Squeezle42** [comment]
I'll post for review when the water goes away, I'm not very good at
explaining it
