### ISSUE TITLE
Disabling gpu (-G) affects other programs running opencl

### ISSUE THREAD

**Issue by murrayf** [luke-jr/bfgminer#280]
Hello,

When I use bfgminer disabling gpu, other programs using opencl like boinc (boinc.berkeley.edu) cannot see my gpu and stop working.

Could be possible as enhacement disabling gpu in bfgminer but keep on seekable for other software like boinc?

Thanks a lot,

Alberto.

:)

**Comment by luke-jr** [comment]
That's odd, I can't imagine why it would behave that way... -G (and the newer -S opencl:noauto) work by never even loading the OpenCL libraries. Does it work any better if you compile without OpenCL support at all?

**Comment by murrayf** [comment]
No, boinc says there is no gpu, I'd like bfgminer disabling gpu (if necessary) but allowing other programs using opencl features

**Comment by luke-jr** [comment]
BFGMiner does nothing at all to interfere with other software using OpenCL, whether the device is enabled, disabled, or not loaded at all (what -G does). I wonder if something else it does may be related, but we'll probably have to debug this by trial and error :(

**Comment by murrayf** [comment]
Hi again,

You were right -S opencl:noauto allows me to use also opencl in boinc.

Thanks.
