### ISSUE TITLE
Easyminer Internet Explorer Script crashes laptop ? 

### ISSUE THREAD

**Issue by SkyzaLimit** [luke-jr/bfgminer#283]
NHey I got a 30gh BFL and it ran for 5 days the I
![screenshot_2013-09-20-11-48-41](https://f.cloud.github.com/assets/5503697/1182771/0c3f6d6e-2222-11e3-96d1-ff3026a648e6.png)
 get errors from Internet Explorer saying a script is slowing it down and could cause it to become unresponsive. I kept closingnit but it keeps opening.  Then my laptop went down a couple days later I cant get it running now . So I switched to another and mined for 7 days and now im getting the same Internet Explorer Script error.  INTERNET EXPLORER isnt running at all . 

Any help resulting in a fix will get a btc tip from me . 

Thanx

**Comment by Flowk5** [comment]
Not sure if this is still and issue for you or not. If you are running Easy Miner, you are actually running Internet Explorer. The graphs that show at the bottom of the program are actually iframes that point to an HTML file that is saved in at %appdata%\local\temp directory. Tips on stopping the error.. go into IE. tools>internet options> advanced tab. Make sure the box is unchecked that is labeled "Display a notification about every script error."

You might also want to try this fix it : http://support.microsoft.com/kb/175500

Hope this helps someone. Thanks.

1KKcvrXp94PcPWiNtCmgxgBZC3duipfL5t

**Comment by luke-jr** [comment]
Sounds like this isn't BFGMiner-related...
