### ISSUE TITLE
Problem compiling bfgminer

### ISSUE THREAD

**Issue by hb4ch** [luke-jr/bfgminer#296]
I am currently using Fedora 19, and when I was trying to compile bfgminer, I got trapped in the libcurl problem. When I ran"./configure", it showed me that I had to have a higher version of libcurl,so I did. I ran "yum install libcurl" but there seemed to be a multi-lib protection issue(which I think it's the repo's fault). So I gave up yum, and went to the official site of cURL and downloaded the tarballs and I compiled withouted a problem. However ,the configure of bfgminer doesn't seem to recognize the newly installed curl, and the error remains. I tried "./configure LIBCURL_LIBS=/usr/local/lib" (where I have checked where the new libcurl installed), it doesn't solved the problem.

**Comment by luke-jr** [comment]
This is an OS configuration problem. I don't think Fedora has /usr/include paths in its default configuration.
