### ISSUE TITLE
hashbuster support

### ISSUE THREAD

**Issue by vpereira** [luke-jr/bfgminer#301]
Hi, there is a new hasher, named hashbuster, based on the bitfury chip. any chance to get it support? what do you need, beside a hardware, to port it?

**Comment by luke-jr** [comment]
Some (at least basic) documentation of the interface is needed to write the initial driver - or discussion with someone familiar with it.

**Comment by TrooperT** [comment]
looks like it uses the HIDapi from: https://bitcointalk.org/index.php?topic=293668.msg3234977#msg3234977

**Comment by vpereira** [comment]
and their cgminer customized version is here https://www.dropbox.com/s/d91e7e64r5zfujt/v0.7_fix_resetchip_chipdetect.tar.bz2
