### ISSUE TITLE
compilation failed on kncminer (BeagleBoard)

### ISSUE THREAD

**Issue by sickpig** [luke-jr/bfgminer#306]
I've used this instructions: 

http://codepad.org/QKSeO5zh

everything worked till this command: 

make AR=arm-angstrom-linux-gnueabi-ar  (row 27) 

that fails with this error: 

make[2]: Entering directory `/home/root/bfgminer'
  CC       bfgminer-miner.o
miner.c:199:6: error: conflicting type qualifiers for 'have_libusb'
In file included from ./sha2.h:36:0,
                 from miner.c:58:
./miner.h:914:13: note: previous declaration of 'have_libusb' was here
make[2]: *** [bfgminer-miner.o] Error 1
make[2]: Leaving directory`/home/root/bfgminer'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/home/root/bfgminer'
make: **\* [all] Error 2

i've dig a bit a found out that have_libusb was defined as external in miner.h in this quite recent commit:  

commit 24d4e7f256d31095a86b4f6f36c8d9943d958dd4
Author: Luke Dashjr <luke-jr+git@utopios.org>
Date:   Tue Oct 15 01:04:58 2013 +0000

```
Abstract ft232r scan+probe interface into new generic lowlevel driver interface
```

**Comment by luke-jr** [comment]
Fixed in d03725a, thanks!
