### ISSUE TITLE
MinGW/MSYS Make Error Unknown Type Name 'int64_t'

### ISSUE THREAD

**Issue by jwilliams31** [luke-jr/bfgminer#310]
I am trying to build bfgminer on Windows 7 (32-bit) using MinGW/MSYS following the windows-build.txt directions.  I am to the point of trying to make the executable, and I get this:

In file included from logging.h:33:0,
                 from hexdump.c:22:
util.h:131:41: error: unknown type name 'int64_t'
 void us_to_timeval(struct timeval _val, int64_t us);
                                         ^
util.h:132:44: error: unknown type name 'int64_t'
 void us_to_timespec(struct timespec *spec, int64_t us);
                                            ^
util.h:133:44: error: unknown type name 'int64_t'
 void ms_to_timespec(struct timespec *spec, int64_t ms);
                                            ^
util.h:136:17: error: unknown type name 'int64_t'
 void cgsleep_us(int64_t us);
                 ^
util.h:140:43: error: unknown type name 'int64_t'
 void (_cgsleep_us_r)(cgtimer_t _ts_start, int64_t us);
                                           ^
util.h:190:2: error: unknown type name 'uint8_t'
  uint8_t *buf;
  ^
make[2]: *_\* [bfgminer-hexdump.o] Error 1
make[2]: Leaving directory `/home/jwilliams/bfgminer'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/jwilliams/bfgminer'
make: **\* [all] Error 2

Any thoughts?

Thank you.

**Comment by luke-jr** [comment]
Easy fix, just add to the top of util.h:

```
#include <stdint.h>
```

Working on something else right now, so adding this to git will need to wait a bit.

**Comment by jwilliams31** [comment]
That did it.

Thank you!

**Comment by luke-jr** [comment]
Fixed in 2546c05
