### ISSUE TITLE
Make error dlclose@@GLIBC_2.2.5

### ISSUE THREAD

**Issue by gades** [luke-jr/bfgminer#315]
Please add to config : ./configure LIBS="-ldl"
otherwise there is a problem with linking:

make[3]: Leaving directory `/home/gades/src/bfgminer/libblkmaker'
  CCLD   bfgminer
/usr/bin/ld: bfgminer-lowl-hid.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib/x86_64-linux-gnu/libdl.so.2 so try adding it to the linker command line
/lib/x86_64-linux-gnu/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [bfgminer] Error 1
make[2]: Leaving directory`/home/gades/src/bfgminer'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/home/gades/src/bfgmine

**Comment by luke-jr** [comment]
Please confirm this is fixed in latest git (9684782 in particular) and close if so.

**Comment by gades** [comment]
I confirm that the problem is solved.

11 íîÿá. 2013, â 21:55, Luke-Jr notifications@github.com íàïèñàë(à):
