### ISSUE TITLE
Segmentation fault on 3.3.0

### ISSUE THREAD

**Issue by Nikg92** [luke-jr/bfgminer#317]
Sorry I accidentally hit enter and prematurely opened the issue without a comment.
I've been getting segmentation faults at random intervals. The application will run for hours and then suddenly crash. 

I will try 3.5.2 and 3.2.6.

Tested versions: 3.6 and 3.3

Operating System: Ubuntu 13.04 64-bit
Hardware: BFL ASIC (5 Gh/s Unit)

I'm not quite sure of what log data to provide but it does say that it was caused by SIGSEGV in __libc_start_main()

Crash Log (removed core dump & Process Maps):
ProblemType: Crash
Architecture: amd64
CrashCounter: 1
Date: Thu Nov 14 01:26:40 2013
DistroRelease: Ubuntu 13.04
ExecutablePath: /usr/bin/bfgminer
ExecutableTimestamp: 1382745844
ProcCmdline: /usr/bin/bfgminer --debuglog
ProcCwd: /home/nik
ProcEnviron:
 TERM=xterm
 SHELL=/bin/bash
 PATH=(custom, no user)
 LANG=en_US.UTF-8
 XDG_RUNTIME_DIR=<set>
ProcStatus:
 Name:  bfgminer
 State: S (sleeping)
 Tgid:  5281
 Pid:   5281
 PPid:  5218
 TracerPid: 0
 Uid:   1000    1000    1000    1000
 Gid:   1000    1000    1000    1000
 FDSize:    64
 Groups:    4 20 24 27 30 46 108 124 1000 
 VmPeak:      882956 kB
 VmSize:      817820 kB
 VmLck:        0 kB
 VmPin:        0 kB
 VmHWM:     7384 kB
 VmRSS:     7384 kB
 VmData:      705752 kB
 VmStk:      136 kB
 VmExe:      584 kB
 VmLib:    12424 kB
 VmPTE:      320 kB
 VmSwap:           0 kB
 Threads:   12
 SigQ:  0/28219
 SigPnd:    0000000000000000
 ShdPnd:    0000000000000000
 SigBlk:    0000000000000000
 SigIgn:    0000000000001000
 SigCgt:    0000000188084002
 CapInh:    0000000000000000
 CapPrm:    0000000000000000
 CapEff:    0000000000000000
 CapBnd:    0000001fffffffff
 Seccomp:   0
 Cpus_allowed:  f
 Cpus_allowed_list: 0-3
 Mems_allowed:  00000000,00000001
 Mems_allowed_list: 0
 voluntary_ctxt_switches:   246
 nonvoluntary_ctxt_switches:    221
Signal: 11
Uname: Linux 3.8.0-33-generic x86_64
UserGroups: adm cdrom dialout dip lpadmin plugdev sambashare sudo

**Comment by luke-jr** [comment]
Not supporting ancient versions. Upgrade to 3.5.2 or downgrade to 3.2.6.

**Comment by luke-jr** [comment]
And if you still get a segfault, include actual information in the bug report...
