### ISSUE TITLE
Asks for URL if first pool in conf uses userpass

### ISSUE THREAD

**Issue by Mitronic** [luke-jr/bfgminer#319]
I have BFGMiner 3.6.0 setup to run from a batch file that calls a specific conf file.  If the first pool in the conf file is set to use "userpass" : "username:password" instead of "user" : "username", "pass" : "password", BFGMiner stops and asks for URL.  If I replace the first pool with one that uses both user and pass, BFGMiner loads normally.

**Comment by luke-jr** [comment]
Fixed in 3f21b2b
