### ISSUE TITLE
Fedora 15 Compile Issue

### ISSUE THREAD

**Issue by machejc** [luke-jr/bfgminer#324]
I run Fedora 15 on my server and there is no rpm available for uthash-dev. After copying the contents of uthash-master/src to the bfgminer-3.6.0 directory, when I do a ./configure I get an error message:

checking whether HASH_ITER is declared... no
configure: error: Could not find HASH_ITER - please install uthash-dev 1.9.2+

How do I install uthash manually on Fedora 15?

-- Mache

**Comment by luke-jr** [comment]
Fedora 15 has been EOL since June 2012, probably has known security issues, and should not be used for anything.

Installing uthash consists of placing the headers in your system include path.
