### ISSUE TITLE
Cannot see my GPUs

### ISSUE THREAD

**Issue by sajmonTM** [luke-jr/bfgminer#325]
After the update on v3.6.0, BFGMiner cannot see any of my GPUs.
With  v3.3.0 everything was OK

**Comment by nergdron** [comment]
If you're talking about the packages from my PPA, yes, we're aware there's been a build problem on Launchpad. I'm looking into it, and will hopefully have updated packages which fix the issue soon. In the mean time, it should be safe to roll back to v3.3.0.

**Comment by sajmonTM** [comment]
Yes, this is what I had in mind. 

Btw, how to roll back to v3.3.0 ??
Thank you

**Comment by nergdron** [comment]
The Ubuntu help site has some examples on how to install a specific package version:

http://askubuntu.com/questions/138284/how-to-downgrade-a-package-via-apt-get

**Comment by nergdron** [comment]
Alright, updated 3.6.0 package is in my PPA and seems to fix this issue.

**Comment by sajmonTM** [comment]
you are a great guy 
thx
