### ISSUE TITLE
Compilation issue undefined reference

### ISSUE THREAD

**Issue by achow101** [luke-jr/bfgminer#327]
I am trying to compile the latest version of bfgminer on a 64 bit Windows 7 machine using MinGW. I am compiling it with cpumining enabled. Upon compiling, this error appears:

bfgminer-miner.o:miner.c:(.text+0xc741): undefined reference to 'llround'

**Comment by luke-jr** [comment]
```
make AM_V_CCLD=
```

Please post the very long line at the end.

**Comment by achow101** [comment]
This is the entire output

$ make AM_V_CCLD=
make  all-recursive
make[1]: Entering directory `/d/data/bitcoin/bfgminer'
Making all in lib
make[2]: Entering directory`/d/data/bitcoin/bfgminer/lib'
make  all-recursive
make[3]: Entering directory `/d/data/bitcoin/bfgminer/lib'
make[4]: Entering directory`/d/data/bitcoin/bfgminer/lib'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory`/d/data/bitcoin/bfgminer/lib'
make[3]: Leaving directory `/d/data/bitcoin/bfgminer/lib'
make[2]: Leaving directory`/d/data/bitcoin/bfgminer/lib'
Making all in ccan
make[2]: Entering directory `/d/data/bitcoin/bfgminer/ccan'
make[2]: Nothing to be done for`all'.
make[2]: Leaving directory `/d/data/bitcoin/bfgminer/ccan'
Making all in libblkmaker
make[2]: Entering directory`/d/data/bitcoin/bfgminer/libblkmaker'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory`/d/data/bitcoin/bfgminer/libblkmaker'
Making all in x86_32
make[2]: Entering directory `/d/data/bitcoin/bfgminer/x86_32'
make[2]: Nothing to be done for`all'.
make[2]: Leaving directory `/d/data/bitcoin/bfgminer/x86_32'
make[2]: Entering directory`/d/data/bitcoin/bfgminer'
make -C lib
make[3]: Entering directory `/d/data/bitcoin/bfgminer/lib'
make  all-recursive
make[4]: Entering directory`/d/data/bitcoin/bfgminer/lib'
make[5]: Entering directory `/d/data/bitcoin/bfgminer/lib'
make[5]: Nothing to be done for`all-am'.
make[5]: Leaving directory `/d/data/bitcoin/bfgminer/lib'
make[4]: Leaving directory`/d/data/bitcoin/bfgminer/lib'
make[3]: Leaving directory `/d/data/bitcoin/bfgminer/lib'
gcc -std=gnu99 -DHAS_YASM -O2 -msse2 -pthread -Llibblkmaker/.libs -Wl,-rpath,\$O
RIGIN/libblkmaker/.libs    -o bfgminer.exe bfgminer-miner.o bfgminer-deviceapi.o
 bfgminer-util.o bfgminer-sha2.o bfgminer-api.o bfgminer-logging.o    bfgminer-d
river-opencl.o bfgminer-ocl.o bfgminer-findnonce.o bfgminer-adl.o  bfgminer-sha2
56_generic.o bfgminer-sha256_via.o bfgminer-sha256_cryptopp.o bfgminer-sha256_ss
e2_amd64.o bfgminer-sha256_sse4_amd64.o bfgminer-sha256_altivec_4way.o bfgminer-
driver-cpu.o bfgminer-lowl-vcom.o  bfgminer-lowl-usb.o bfgminer-binloader.o bfgm
iner-lowlevel.o bfgminer-dynclock.o bfgminer-driver-bitforce.o bfgminer-driver-b
igpic.o bfgminer-driver-icarus.o bfgminer-driver-cairnsmore.o bfgminer-driver-er
upter.o bfgminer-driver-avalon.o bfgminer-hexdump.o  bfgminer-driver-klondike.o
bfgminer-driver-modminer.o bfgminer-driver-x6500.o bfgminer-ft232r.o bfgminer-jt
ag.o bfgminer-driver-ztex.o bfgminer-libztex.o bfgminer-driver-bitfury.o bfgmine
r-libbitfury.o bfgminer-spidevc.o   bfgminer-driver-littlefury.o     -Lc:/MinGW/
lib -lcurl -lcurldll   -Lc:/MinGW/lib -ljansson -lpthread -lpdcursesw  -lws2_32
-Lc:/MinGW/lib -lusb-1.0   -lwinmm  -lm lib/libgnu.a ccan/libccan.a -lsetupapi -
lblkmaker_jansson-0.1 -lblkmaker-0.1    libsse2cpuminer.a  x86_32/libx8632.a
bfgminer-miner.o:miner.c:(.text+0xc741): undefined reference to`llround'
collect2.exe: error: ld returned 1 exit status
make[2]: **\* [bfgminer.exe] Error 1
make[2]: Leaving directory `/d/data/bitcoin/bfgminer'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/d/data/bitcoin/bfgminer'
make: **\* [all] Error 2

**Comment by luke-jr** [comment]
I think there must be something broken with your MingW then... normal MingW does support llround since at least 2008. Where did you get it?

**Comment by achow101** [comment]
the latest from mingw.org. I have reinstalled in several times and the same error has come up

**Comment by luke-jr** [comment]
Maybe try http://mingw-w64.sourceforge.net/

**Comment by achow101** [comment]
I'm not sure what to do with that. However, if I go into miner.c and change 'llround' at line 7426 to 'lround' the program builds. It also runs but I am not sure whether that will break it or not.

**Comment by luke-jr** [comment]
lround may break over 4 Gh/s total hashrate.
This would be safe:

```
global_hashrate = ((long long)lround(total_rolling)) * 1000000;
```

But lround and llround are from the same C99 standard...

**Comment by achow101** [comment]
well that works. Thanks.

**Comment by luke-jr** [comment]
Looks like this is a problem with mingw.org's version, long since fixed in the mingw64 fork. Pushed a workaround in 0230ba4 anyway.
