### ISSUE TITLE
Jansson dependency error on PKG_CONFIG_PATHed compile

### ISSUE THREAD

**Issue by frankvolkel** [luke-jr/bfgminer#328]
Hi. I'm trying to compile bfgminer on a HPC cluster. I ran ./configure with PKG_CONFIG_PATH to my downloaded and compiled jansson-2.5 and curl-7.33.0 paths in my home directory; I do not have admin access. Configure ends properly (see output below), but when I ran make, I got the following error: 

blkmaker_jansson.c:19:21: error: jansson.h: No such file or directory
blkmaker_jansson.c:27:3: error: #error "Jansson 2.0 with long long support required!"

---
## bfgminer 3.0.10

Configuration Options Summary:

  curses.TUI...........: FOUND: ncursesw
  scrypt...............: Disabled

  OpenCL...............: Enabled
    ADL.monitoring.....: Enabled
  Avalon.ASICs.........: Disabled
  BitForce.devices.....: Enabled
  Icarus.FPGAs.........: Enabled
  ModMiner.FPGAs.......: Enabled
  X6500.FPGAs..........: Disabled (libusb not found)
  ZTEX.FPGAs...........: Disabled (libusb not found)
  libudev.detection....: no

  CPU Mining...........: Disabled

Compilation............: make (or gmake)
  CPPFLAGS.............: -pthread
  CFLAGS...............: -g -O2 -I/usr/local/include -pthread -Ilibblkmaker
  LDFLAGS..............: -pthread -lpthread -Llibblkmaker/.libs -Wl,-rpath,\$$ORIGIN/libblkmaker/.libs,-zorigin
  LDADD................: -ldl -L/usr/local/lib -lcurl -L/usr/local/lib -ljansson -lncursesw -lm -lblkmaker_jansson-0.1 -lblkmaker-0.1

Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local

**Comment by luke-jr** [comment]
Will need at least config.log uploaded somewhere

**Comment by frankvolkel** [comment]
config.log as requested =) http://pastebin.com/nFNRjS5E

**Comment by luke-jr** [comment]
How did you install the libraries to your home directory?

**Comment by frankvolkel** [comment]
I simply compiled them (make); I do not have root access on these machines to install them (make install).

**Comment by luke-jr** [comment]
Try rebuilding them with ./configure --prefix=/home/user/wherever/else/you/want/them/under

**Comment by frankvolkel** [comment]
Configure fails with an error: 

configure: error: Could not find jansson library

**Comment by luke-jr** [comment]
config.log...

**Comment by frankvolkel** [comment]
Configure didn't complete so config.log was not updated. I placed PKG_CONFIG_PATH in environment and had path set as well so as to obtain a successful configure run: http://pastebin.com/KSRvyXHe

make still fails at the same line though.

**Comment by luke-jr** [comment]
The --prefix was to reinstall _the libraries_ with.

**Comment by frankvolkel** [comment]
Ah yes that did the trick, thanks!
