### ISSUE TITLE
Pools not recognized in .conf file

### ISSUE THREAD

**Issue by punin** [luke-jr/bfgminer#33]
Build BFL on RPi, copied ~/.cgminer/cgminer.conf to ~/.bfgminer/bfgminer.conf.

When starting, bfgminer asks to enter at least 1 pool. cgminer.conf had several pools, and the conf file worker perfectly with cgminer 2.5.

Entered pool info on bfminer startup, wrote to config file. Opened config file to check for anything weird, all seemed normal. Restarted bfgminer, again it asked for a pool.

**Comment by luke-jr** [comment]
Fixed in 4eb92d0
