### ISSUE TITLE
can not change to Nvidia discrete graphics

### ISSUE THREAD

**Issue by whyb** [luke-jr/bfgminer#341]
hello Luke,
I have a Intel (R) Core (TM) i7 CPU and a Nvidia discrete graphics:GeForce GT640M in win7 64bit,
But the need to manually manage the device after each start, Enter the 'M+' post after entering 'auto', joined only OCL0, use gpu-z found my integrated graphics used 100%.
if input 'all' show 'not found device'.  Where can I find my device ID or device name, and join it?

thanks very much

**Comment by luke-jr** [comment]
Already documented in README.GPU
