### ISSUE TITLE
make[2]: *** [libblkmaker_jansson-0.1.la] Error 1

### ISSUE THREAD

**Issue by geeeoff** [luke-jr/bfgminer#347]
trying to compile latest bfgminer for Win x64

having issue linking jansson lib (I think) - jansson compiled and linked fine

config.log: http://pastebin.com/Ay8cdype
make error: http://pastebin.com/Uzz0ej45

**Comment by luke-jr** [comment]
JANSSON_LIBS should be of format '-L/path/to/lib -ljansson' or similar.

**Comment by geeeoff** [comment]
thanks, that worked
