### ISSUE TITLE
GPU monitoring & setup not working

### ISSUE THREAD

**Issue by punin** [luke-jr/bfgminer#35]
Building on Debian claims GPU monitoring support is enabled, but when BFGMiner starts, all GPU's show as OCL and no fan nor engine & memspeed readouts are shown. 

 [P]ool management [G]PU management [S]ettings [D]isplay options [Q]uit
 OCL  0: 299.7/317.8/246.7Mh/s | A:32 R:0 HW: 0 U: 3.45/m
 OCL  1: 388.8/410.2/277.6Mh/s | A:36 R:0 HW: 0 U: 3.88/m

No error is shown when starting up using:

bfgminer --auto-fan --auto-gpu --temp-target 70 --gpu-engine 750-850,850-940 --gpu-memclock 300 --gpu-vddc 1.02,1.06 -I 9

Configuration Options Summary:

  curses.TUI...........: FOUND: ncurses

  OpenCL...............: Enabled
    ADL................: SDK found, GPU monitoring support enabled
  BitForce.FPGAs.......: Disabled
  Icarus.FPGAs.........: Disabled
  ModMiner.FPGAs.......: Disabled
  Ztex.FPGAs...........: Enabled

  CPU Mining...........: Disabled

Compilation............: make (or gmake)
  CPPFLAGS.............: 
  CFLAGS...............: -O2 -Wall -march=native
  LDFLAGS..............:  -lpthread 
  LDADD................: -ldl -lcurl   compat/jansson/libjansson.a -lpthread    -lm  -lusb-1.0

Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local

**Comment by luke-jr** [comment]
Figured it out?

**Comment by punin** [comment]
yeah, export DISPLAY=:0 FTW
