### ISSUE TITLE
Rasspberry Pi / OpenWRT

### ISSUE THREAD

**Issue by trust2fire** [luke-jr/bfgminer#350]
Wondering if you might find a moment of your time and compile bfgminer for the Raspberry pi running OpenWRT.

Thanks so much for your efforts.

Take care

**Comment by luke-jr** [comment]
What OpenWrt config is this?

**Comment by trust2fire** [comment]
Attitude Adjustment 12.09-rc1

Thanks

**Comment by luke-jr** [comment]
That's the version, not the config... config is like bcm\* and ixp400 etc

**Comment by trust2fire** [comment]
Sorry for the miss understanding. The config is brcm2708.
Raspberry pi B.

Thanks again.

**Comment by luke-jr** [comment]
3.8.1 should now have brcm2708 packages available.

**Comment by trust2fire** [comment]
Thanks much.
