### ISSUE TITLE
Multiple Twinfury slow down Hashrate to one Twinfury

### ISSUE THREAD

**Issue by Bungie** [luke-jr/bfgminer#362]
By running four twinfury with bfgminer 3.9.0 on debian, by using a USB 3.0 Hub (4 Amper).
The Hashrate starts with ca. 20 GH/s, after 20 Minutes the Hashrates decrease until it running only one twinfury.

Sometimes I get a "Query timeout" from one chip and on the time the Hardware errors increase up to 80%.

**Comment by luke-jr** [comment]
?

**Comment by Bungie** [comment]
I was testing your latest changes and all four twinfury's running on 
full speed for 20 Minutes
then I noticed that the poweradapter from the usb hub is melting.

I'm not sure that the Hub was already defect.

Am 06.01.2014 22:18, schrieb Luke-Jr:

**Comment by fbgithub** [comment]
Twinfurys often behave quite odd, that's why I changed to other devices and have no problems anymore. I also noticed that only one chip is working properly after some 20 mins in the past, and they are also producing an awful amount of duplicate shares.
