### ISSUE TITLE
RaspberryPi + BFGMiner + Mediaplayer Daemon (MPD)

### ISSUE THREAD

**Issue by ghost** [luke-jr/bfgminer#380]
First of all, Thanks for your great work!!

I found an issue when running BFGMiner  under Raspbian. If bfgminer and mpd are running simmultaniously the whole Pi crashes and freezes up. Only disconnectiong from power lets the Pi start again.

Tell me wich logfiles are needed, then i will provide them.

Happend with BFGMiner 3.9.0 and 3.10.0.

BR
faithless

**Comment by luke-jr** [comment]
Sounds like a Pi hardware problem.

**Comment by ghost** [comment]
Generaly a Pi-Problem, or is it only mine?
