### ISSUE TITLE
bfgminer cause centos kernel error

### ISSUE THREAD

**Issue by chisheng6624** [luke-jr/bfgminer#381]
When i excuted bfgminer with red fury usb miners, bfgminer only found one usb miner and others were dead. If i forced to reset the dead usb miner, the centos crash and got kernel error. System logs are as follow.

Jan 17 20:35:18 kernel: cdc_acm 1-1.3:1.0: ttyACM0: USB ACM device
Jan 17 20:35:18 kernel: cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
Jan 17 20:35:18 kernel: ------------[ cut here ]------------
Jan 17 20:35:18 kernel: WARNING: at fs/sysfs/dir.c:512 sysfs_add_one+0xb8/0xd0() (Tainted: P           ---------------   )
Jan 17 20:35:18 kernel: Hardware name: System Product Name
Jan 17 20:35:18 kernel: sysfs: cannot create duplicate filename '/dev/char/166:0'
Jan 17 20:35:18 kernel: Modules linked in: dahdi_echocan_oslec(U) echo(U) xpp_usb(U) xpp(U) wctc4xxp(U) dahdi_transcode(U) wcb4xxp(U) wctdm(U) wcfxo(U) wctdm24xxp(U) wcte11xp(U) wct1xxp(U) wcte12xp(U) dahdi_voicebus(U) wct4xxp(U
) dahdi(U) ipt_REJECT i2c_dev cp210x usbserial cdc_acm hptiop fuse autofs4 hwmon_vid crc_ccitt cpufreq_ondemand powernow_k8 freq_table mperf ipv6 xt_multiport iptable_filter iptable_mangle ipt_MASQUERADE iptable_nat nf_nat nf_conntrack_i
pv4 nf_conntrack nf_defrag_ipv4 ip_tables uinput ppdev microcode k8temp edac_core edac_mce_amd skge osst st snd_mpu401 snd_mpu401_uart snd_rawmidi parport_pc parport asus_atk0110 forcedeth sg snd_intel8x0 snd_ac97_codec ac97_bus snd_seq
snd_seq_device snd_pcm snd_timer snd soundcore snd_page_alloc i2c_nforce2 ext4 jbd2 mbcache sr_mod cdrom sd_mod crc_t10dif firewire_ohci firewire_core crc_itu_t sata_sil aic7xxx scsi_transport_spi rr62x(P)(U) sata_nv pata_acpi ata_generi
c pata_amd nouveau ttm drm_kms_helper drm i2c_algo_bit i2c_core mxm_wmi video out
Jan 17 20:35:18 kernel: put wmi dm_mirror dm_region_hash dm_log dm_mod [last unloaded: echo]
Jan 17 20:35:18 kernel: Pid: 15232, comm: probe_usb:001:0 Tainted: P           ---------------    2.6.32-431.3.1.el6.x86_64 #1
Jan 17 20:35:18 kernel: Call Trace:
Jan 17 20:35:18 kernel: [<ffffffff81071e27>] ? warn_slowpath_common+0x87/0xc0
Jan 17 20:35:18 kernel: [<ffffffff81071f16>] ? warn_slowpath_fmt+0x46/0x50
Jan 17 20:35:18 kernel: [<ffffffff81205f28>] ? sysfs_add_one+0xb8/0xd0
Jan 17 20:35:18 kernel: [<ffffffff812063bb>] ? sysfs_do_create_link+0x12b/0x170
Jan 17 20:35:18 kernel: [<ffffffff81206433>] ? sysfs_create_link+0x13/0x20
Jan 17 20:35:18 kernel: [<ffffffff8136a947>] ? device_add+0x317/0x650
Jan 17 20:35:18 kernel: [<ffffffff8137396b>] ? pm_runtime_init+0xcb/0xe0
Jan 17 20:35:18 kernel: [<ffffffff8136ac9e>] ? device_register+0x1e/0x30
Jan 17 20:35:18 kernel: [<ffffffff8136ad98>] ? device_create_vargs+0xe8/0x110
Jan 17 20:35:18 kernel: [<ffffffff8136adf1>] ? device_create+0x31/0x40
Jan 17 20:35:18 kernel: [<ffffffff8150c72c>] ? klist_add_tail+0x3c/0x50
Jan 17 20:35:18 kernel: [<ffffffff8133219e>] ? tty_register_device+0x9e/0x140
Jan 17 20:35:18 kernel: [<ffffffff813bc3d2>] ? usb_unlocked_enable_lpm+0x42/0x50
Jan 17 20:35:18 kernel: [<ffffffff8128461a>] ? kobject_get+0x1a/0x30
Jan 17 20:35:18 kernel: [<ffffffffa00e8a16>] ? acm_probe+0x1046/0x1460 [cdc_acm]
Jan 17 20:35:18 kernel: [<ffffffff8120556e>] ? sysfs_addrm_finish+0x4e/0x270
Jan 17 20:35:18 kernel: [<ffffffff813cc0d6>] ? usb_probe_interface+0x116/0x2e0
Jan 17 20:35:18 kernel: [<ffffffff8136d963>] ? driver_probe_device+0x143/0x2a0
Jan 17 20:35:18 kernel: [<ffffffff8136db70>] ? __device_attach+0x0/0x60
Jan 17 20:35:18 kernel: [<ffffffff8136dbc3>] ? __device_attach+0x53/0x60
Jan 17 20:35:18 kernel: [<ffffffff8136caf4>] ? bus_for_each_drv+0x64/0x90
Jan 17 20:35:18 kernel: [<ffffffff8136dca4>] ? device_attach+0xa4/0xc0
Jan 17 20:35:18 kernel: [<ffffffff813d326d>] ? proc_ioctl+0x1cd/0x250
Jan 17 20:35:18 kernel: [<ffffffff813d3c22>] ? usbdev_ioctl+0x932/0x1750
Jan 17 20:35:18 kernel: [<ffffffff8119dbac>] ? vfs_ioctl+0x7c/0xa0
Jan 17 20:35:18 kernel: [<ffffffff8119dcf4>] ? do_vfs_ioctl+0x84/0x580
Jan 17 20:35:18 kernel: [<ffffffff8118972f>] ? vfs_read+0x12f/0x1a0
Jan 17 20:35:18 kernel: [<ffffffff8119e271>] ? sys_ioctl+0x81/0xa0
Jan 17 20:35:18 kernel: [<ffffffff810e1e6e>] ? __audit_syscall_exit+0x25e/0x290
Jan 17 20:35:18 kernel: [<ffffffff8100b072>] ? system_call_fastpath+0x16/0x1b
Jan 17 20:35:18 kernel: ---[ end trace 9fb6feb363bd8e2d ]---

**Comment by luke-jr** [comment]
This is a problem with your system, not BFGMiner. Furthermore, since your kernel is tainted, you won't get any support from Linux developers either...
