### ISSUE TITLE
libjansson4 is not installable

### ISSUE THREAD

**Issue by CorySvensson** [luke-jr/bfgminer#397]
Hello,

Trying install BFGMiner, and it says that libjansson4 is required, but it's not installable.

This is on Ubuntu 13.10 -- just days ago I was able to do this on Xubuntu 13.10.

**Comment by luke-jr** [comment]
OS problems are not BFGMiner issues...?

**Comment by CorySvensson** [comment]
Sorry for the ignorance, but isn't it your installer that's referencing libjansson4 as a dependency?  Or is it the OS making that reference?  Or could it just be a repository that's changed?

If this was like, solaris, ok, but it's a virgin install of Ubuntu live USB, I wouldn't expect dependencies to be broken for this, and from what I can tell, it was working on 13.10, so I'm not sure where I'm going wrong.

**Comment by luke-jr** [comment]
BFGMiner needs libjansson4, yes. That's unavoidable, even if your OS was missing a package for it.

http://packages.ubuntu.com shows the package exists for all releases, though, so...

**Comment by nergdron** [comment]
Looks like it's available in the "universe" repository, which isn't enabled by default on the Ubuntu USBs / ISOs. Enable that, and it should work fine.

**Comment by CorySvensson** [comment]
Awesome, thanks guys.
