### ISSUE TITLE
Working with MinePeon - BFGminer - keep getting hacked - please help.

### ISSUE THREAD

**Issue by XianStudio** [luke-jr/bfgminer#398]
Hi all - your input would be greatly appreciated - 

I have minepeon installed (via rasp pi) -- I have a 25 character PW and I keep getting some hacker add his wallet to my miner -- Basically I have to log in and kick him off every hour ... he is stealing hashes from me and pissing me off.  I've changed the static IP and Gateway once and he came back. -- I do NOT have a keyboard or monitor connected so he is not using a keystroke device.  Do any of you have any idea how to kick this guy off? 

-- I should add - I have a NetGear Firewall that I will be installing early next week and currently there is NO firewall -- just the ethernet cord from the cabinet into my mining device (a 500GH butterfly machine) ---  Also -- ANY advice on how to set up this firewall would also be greatly appreciated. 
![hack](https://f.cloud.github.com/assets/5586265/2176748/dfcc7e2c-95dd-11e3-8fb1-d29c60311afd.png)

**Comment by luke-jr** [comment]
Sounds like a weak password to me...
