### ISSUE TITLE
function "hashfast_temperature_conv" of "driver-hashfast.c" has a bug

### ISSUE THREAD

**Issue by Danyu-Wu** [luke-jr/bfgminer#399]
static inline
float hashfast_temperature_conv(const uint8_t \* const data)
{
    // Temperature is 12-bit fraction ranging between -61.5 C and ~178.5 C
    uint32_t tempdata = ((uint32_t)data[1] << 8) | data[0];
    tempdata &= 0xfff;
    tempdata *= 240;
    tempdata -= 251904;  // 61.5 \* 4096   //here!!!
    float temp = tempdata;
    temp /= 4096.;
    return temp;
}

the "tempdata" is an unsigned integer, may have overflow problem

**Comment by luke-jr** [comment]
Good catch - does your unit actually get that cold? ;)

Fixed in 051909d
