### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [luke-jr/bfgminer#401]
I would like to point out that identifiers like "[`__DEVICEAPI_H__`](https://github.com/luke-jr/bfgminer/blob/cd8069db6bc6fc70790646fdf19f197db7566e28/deviceapi.h#L1)" and "[`__LOGGING_H__`](https://github.com/luke-jr/bfgminer/blob/e9d47e748d2c67649cca431563d2223f8cfb36e4/logging.h#L11)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by luke-jr** [comment]
I do not understand why _max_limit in "Noncompliant Code Example (File Scope Objects)" is considered non-compliant. It is a file-scoped variable, which the C standard quoted seems to reserve the underscore prefix specifically for.

I will fix the header identifiers in BFGMiner header identifiers. However, it seems inappropriate to do so in the standard OpenCL headers. How does _GNU_SOURCE fit in?

**Comment by luke-jr** [comment]
Fixed in 0459dd0

**Comment by elfring** [comment]
Thanks for this [source code improvement](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797).
