### ISSUE TITLE
Strange pool number behavior in "Pool Management" section

### ISSUE THREAD

**Issue by fbgithub** [luke-jr/bfgminer#404]
I have three pools set in my bfgminer configuration numbered autoincrementally 0,1,2 (set by bfgminer), looking like the following in my list:
0: Enabled  Strtm Quota 1 Pool 1: stratum+tcp:....
1: Enabled  Strtm Quota 8 Pool 0: stratum+tcp:....
2: Enabled  Strtm Quota 0 Pool 2: stratum+tcp:....

So if I wanted for example to change my quota settings for pool 1 (which is the first pool in my configuration), I'd choose "change quota" and bfgminer would ask me for the pool number I want to edit and I would then type "0".
When I select "0" I am acutally editing the second pool in my list numbered "1" in front but stated "Pool 0". See what I mean?

By the way "Pool 1" actually just represents a pool with priority 1, so something is quite confusing, isn't it?

**Comment by luke-jr** [comment]
No, the list is sorted and numbered by priority. "Pool 1" means pool 1...
