### ISSUE TITLE
Logging - log file rotation/release logfile between writes

### ISSUE THREAD

**Issue by MrNebrot** [luke-jr/bfgminer#408]
I enabled logging to a text file with bfg, this works great, however depending on the level of output, they can get rather large. Large to review, upload or email, not filesystem large. 

I wrote a vbs script to copy and rename the logfile with a datestamp, so I can archive the logs as well as be able to easily find a specific date/time span that I want to review.

Problem is, I can't null or delete the original log file after generating the archive copy. BFG has it open and locked. 

I can see a few solutions to that:

1) implement a log rotate/archive function, which would remove the need for my external VBscript

2) Release the logfile between writes. Obvious obstacle from the archiver script perspective, is the timing. So that when my log archive job runs, it matches with the time frame where bfg is not writing the log file and has already released it.
I guess there is a way to write a loop which will wait until it can be deleted.

3) open and write to the log file in a fashion which allows the deletion of the file.

Obviously, #1 is preferred but as I doubt this being requested frequently, I am happy to deal with any solution you can provide.

Thanks

**Comment by luke-jr** [comment]
4) Capture the output in some script and do log rotation however you want

**Comment by MrNebrot** [comment]
Capture it how? Via the api?Would you mind elaborating on that? Thank you, much appreciated.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: Luke-JrSent: Sunday, February 23, 2014 8:40 PMTo: luke-jr/bfgminerReply To: luke-jr/bfgminerCc: MrNebrotSubject: Re: [bfgminer] Logging - log file rotation/release logfile between writes (#408)4) Capture the output in some script and do log rotation however you want

—Reply to this email directly or view it on GitHub.

**Comment by luke-jr** [comment]
By default, logging is to standard error.

**Comment by MrNebrot** [comment]
"logging is to standard error"

Luke,
I am sorry to keep bothering you, I certainly would never claim to have the
skill to code something like bfgminer but I have spent decades in the IT
profession, and I just don't know what you mean by that statement. Before
replying, I googled what you stated, figuring it was my lack of knowledge
being the issue here but I could not come with anything to explain that
statement.
I will assume that you may be replying by phone and auto-correct changed
what you wrote.
with that assumption:
"logging is to standard" which standard?
"Standard error" I am getting file lock errors.
"Standard error" I want to capture all output, not just errors.

If I should direct my request, and/or questions elsewhere, please let me
know. I don't mean to pester you if I am reaching out to the wrong
resource.

Sincerely

**Comment by luke-jr** [comment]
http://en.wikipedia.org/wiki/Standard_error_stream#Standard_error_.28stderr.29

**Comment by MrNebrot** [comment]
AH!!! <light bulb>
ok, I gotcha now. I was trying to apply the statement far too limited,
specifically to how bfg functions, what language bfg was written in, which
syntax was supported by the api, etc.
English not being my native language probably didn't help ;)

I think I can work with that...at least I got more avenues to consider and
attempt.
THANK YOU!
I appreciate your contribution in general and most certainly your
willingness to spend your time on answering my most basic questions.

Have a good evening.

Sincerely
