### ISSUE TITLE
compilation fails on OS X

### ISSUE THREAD

**Issue by foshaug** [luke-jr/bfgminer#413]
When trying to compile bfgminer 3.10.0 we fail with the following error:

driver-bitforce.c: In function ‘bitforce_detect_oneof’:
driver-bitforce.c:431: error: unknown field ‘device_fd’ specified in initializer
driver-bitforce.c:431: warning: initialization makes pointer from integer without a cast
make[2]: **\* [bfgminer-driver-bitforce.o] Error 1

**Comment by kryo2k** [comment]
+1

**Comment by luke-jr** [comment]
Do you still have this problem with latest git?

**Comment by kryo2k** [comment]
I didn't get this on OSX, but i got the exact same error on Centos. I believe it was the latest, let me rebuild and check.

**Comment by luke-jr** [comment]
Ah, my workaround was in the monarch branch... merged that. Try latest git now :)

Side note: This is a compiler bug.

**Comment by foshaug** [comment]
This is now compiling on OS X again. Thanks!
