### ISSUE TITLE
Remove my name from the AUTHORS file

### ISSUE THREAD

**Issue by kanoi** [luke-jr/bfgminer#420]
You know the information in there is wrong.
You have ignored git updates to it also.
I prefer my name not being in this copy clone AUTHORS file rather than it being wrong and the FUD you spread being there.

**Comment by luke-jr** [comment]
As I said, if it is wrong, point out what is wrong and how to correct it. It would be wrong to remove it, but I could demote you to the contributors list if you like.

**Comment by kanoi** [comment]
Glad we got your reply documented ... now where's the cyber police for you ignoring my request about my name ...
