### ISSUE TITLE
How to get SysLog to work

### ISSUE THREAD

**Issue by MrNebrot** [luke-jr/bfgminer#421]
You provided me with some ideas as to how i could deal with the extensive logging, and while that was fruitful to some extent, it didn't really work for me (https://github.com/luke-jr/bfgminer/issues/408).

So I decided to go down the road of using Syslog.  I installed WhatsUpGold SysLog server, it is running on the same machine as the BFG instances.  

What I am missing is how I can point the BFG instances to this syslog service.
--syslog alone does not seem to be doing the trick.

thank oyu

**Comment by luke-jr** [comment]
Ensure your system logger is correctly configured for whatever behaviour you desire?

**Comment by MrNebrot** [comment]
There is nothing to configure on the syslogger, as I am sure you know, unless you want it to listen to messages on tcp, it uses UDP:514.  Of course you can configure display and alert options but none of those have anything to do with it actually getting the messages. The source needs to be set to send its messages to the logger. 
I of course tested that it was receiving messages and it does Screenshot of test messages: http://imgur.com/TXf5s7Z
I used sysloggen to create test messages  http://www.snmpsoft.com/freetools/sysloggen.html

What I am asking to get help with is not the syslogger but what syntax, what commands I need to use to set the miner to push the messages to the syslogger. How do I specify the IP/Host, port and protocol?

using --syslog alone obviously is not sufficient. 

How do I set the required values so it will push the messages to my syslogger. 
My logger runs at 192.168.1.212 or localhost on 514

**Comment by luke-jr** [comment]
Uh, that screenshot looks like Windows, which doesn't support syslog... I'm surprised --syslog doesn't give an error?

There is nothing to configure for syslog. See http://man7.org/linux/man-pages/man3/syslog.3.html

**Comment by MrNebrot** [comment]
the windows version of BFGMiner does not support the syslog switch?  That would certainly explain a lot.  I figured that all functions and commands were ported to all platforms unless otherwise notes. 
I guess that could be the reason why the suggestions you made for my first logging issue didn't produce the results you hinted at.

Depending on how/where I apply the --syslog switch, it does complain about it being not recognized. 

As I certainly did not specify that I was using the windows version, for issue https://github.com/luke-jr/bfgminer/issues/408
would you mind revisiting that issue?

And let me know how I can get that to work in windows. 
Unless of course you have some way to enable syslogging in the windows version.  The

**Comment by luke-jr** [comment]
Windows does not support syslog, so I don't see any obvious way to do that...

Issue #408 did not involve syslog, nor does my recommendation there change...
