### ISSUE TITLE
Crash when setting NFY:baud

### ISSUE THREAD

**Issue by nanofury** [luke-jr/bfgminer#425]
Trying to set the SPI baud rate as in the example below results in a crash:

bfgminer --set-device NFY:baud=500000

crashes:
0x495683 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/driver-bitfury.c (690) : in function (_bitfury_set_device_parse_setting)
0x4956c4 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/driver-bitfury.c (697) : in function (bitfury_set_baud)
0x42ef91 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/deviceapi.c (931) : in function (_proc_set_device)
0x42f0b8 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/deviceapi.c (955) : in function (__proc_set_device)
0x42f0e7 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/deviceapi.c (959) : in function (proc_set_device)
0x421c4b : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/miner.c (9773) : in function (cgpu_set_defaults)
0x421e88 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/miner.c (9820) : in function (drv_set_defaults)
0x498a43 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/driver-nanofury.c (264) : in function (nanofury_lowl_probe)
0x4268db : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/miner.c (10853) : in function (probe_device_thread)
Failed to init bfd from (C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\pthreadGC2.dll)
0x6248bbcb : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\pthreadGC2.dll : pthread_create
Failed to init bfd from (C:\Windows\system32\msvcrt.dll)
0x771b2599 : C:\Windows\system32\msvcrt.dll : wcstombs
Failed to init bfd from (C:\Windows\system32\msvcrt.dll)
0x771b26b3 : C:\Windows\system32\msvcrt.dll : beginthreadex
Failed to init bfd from (C:\Windows\system32\kernel32.dll)
0x7600d2e9 : C:\Windows\system32\kernel32.dll : BaseThreadInitThunk
Failed to init bfd from (C:\Windows\system32\ntdll.dll)
0x77471603 : C:\Windows\system32\ntdll.dll : RtlInitializeExceptionChain
Failed to init bfd from (C:\Windows\system32\ntdll.dll)
0x774715d6 : C:\Windows\system32\ntdll.dll : RtlInitializeExceptionChain

C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32>

**Comment by nanofury** [comment]
In a similar way it also crashes when trying to set LED MODE:

bfgminer --set-device NFY:ledmode=alternating

results in:

0x4992a9 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/driver-nanofury.c (480) : in function (nanofury_set_ledmode)
0x42ef91 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/deviceapi.c (931) : in function (_proc_set_device)
0x42f0b8 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/deviceapi.c (955) : in function (__proc_set_device)
0x42f0e7 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/deviceapi.c (959) : in function (proc_set_device)
0x421c4b : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/miner.c (9773) : in function (cgpu_set_defaults)
0x4222a2 : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/miner.c (9930) : in function (bfg_watchdog)
0x42223b : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\bfgminer.exe : /home/luke-jr/public_html/tmp/code/webisect/wr/checkout-Uzljl38AAAEAAEmVX3k
AT/make-release-tmp/49ed3cea5a69171e193f1ea0bdcbe65c7334b119-tmp/miner.c (9910) : in function (watchdog_thread)
Failed to init bfd from (C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\pthreadGC2.dll)
0x6248bbcb : C:\BTC\bfgminer-nanofury-win32\bfgminer-3-10-NF2\49ed3cea5a69171e193f1ea0bdcbe65c7334b119-win32\pthreadGC2.dll : pthread_create
Failed to init bfd from (C:\Windows\system32\msvcrt.dll)
0x771b2599 : C:\Windows\system32\msvcrt.dll : wcstombs
Failed to init bfd from (C:\Windows\system32\msvcrt.dll)
0x771b26b3 : C:\Windows\system32\msvcrt.dll : beginthreadex
Failed to init bfd from (C:\Windows\system32\kernel32.dll)
0x7600d2e9 : C:\Windows\system32\kernel32.dll : BaseThreadInitThunk
Failed to init bfd from (C:\Windows\system32\ntdll.dll)
0x77471603 : C:\Windows\system32\ntdll.dll : RtlInitializeExceptionChain
Failed to init bfd from (C:\Windows\system32\ntdll.dll)
0x774715d6 : C:\Windows\system32\ntdll.dll : RtlInitializeExceptionChain

**Comment by luke-jr** [comment]
I don't see any way for the ledmode crash, but I believe the baud one is fixed in 7414c9e

**Comment by nanofury** [comment]
Luke - thanks for the quick fix!

I tested the "baud" and that one is resolved.

The LEDMODE is still crashing but since this issue was opened for the "baud" one I'm going to close it and I'll open a separate one for the LEDMODE. I think I see a pattern there - it's probably related to trying to do IDENTIFY anything other than the first chip.

**Comment by nanofury** [comment]
Change https://github.com/luke-jr/bfgminer/commit/7414c9e resolves the BAUD issue.
