### ISSUE TITLE
Patch Support Gridseed Blade Miner 

### ISSUE THREAD

**Issue by evolvia31** [luke-jr/bfgminer#431]
Hi, actually bfgminer branch gridseed support the gridseed dualminer which have 5 gc3355 chip on board.
So in the gc3355.h file, the const GC3355_ORB_DEFAULT_CHIPS  is define to 5.

But with the new gridseed Blade (http://hash-master.com/new-gridseed-blade-miner-asic-5-2mh-s-80-chip-scrypt-miner/) each blade have 40 GC3355 chip on board , so
i think to keep compatibility the const GC3355_ORB_DEFAULT_CHIPS will be modifiy by command line to adapt the chip number ?

I think an other variable in command line like 
--set-device gridseed:clock=850,chips=(5|40|x) 
might be add ? 

I'm not very good in C to make a patch.

**Comment by luke-jr** [comment]
Did you confirm that merely changing the constant is sufficient to make it work? Is that with the gridseed branch in this repository, or one of @nwoolls 's branches?

**Comment by evolvia31** [comment]
I can't confirm if this change is the only because i don't test yet, i will receive my griseed blade the next week.  But i think that's the only change to add support.

I confirm this modification will be apply on YOUR bfgminer gridseed branch, nwoolls branch will be modify too but i speak here only to YOUR bfgminer gridseed branch.

**Comment by evolvia31** [comment]
Hi,

I just receive my Gridseed G-Blade today.

After one afternoon of test, Bfgminer is'nt compatible with G-Blade.

Even if I modify GC3355_ORB_DEFAULT_CHIPS  each blade works at 1.6Mh/s against 5.6Mh/s with the cgminer fork of jmordica but it's fork is based on cgminer 3.7.2 which is very old and buggy :(
Actually i think, nwoolls need to review the gc3355.c and .h to add support of 40 chips on one board.

If you need info or debug to add support on this hardware, you can contact me on my email.

**Comment by evolvia31** [comment]
with new version 4.0, g-blade gridseed supoport is added, so i close this ticket.
