### ISSUE TITLE
Miner library? (except of sha256)

### ISSUE THREAD

**Issue by Gargo** [luke-jr/bfgminer#432]
What about to make a library from miner for simple import into another application?

It is just an idea. Consider it please. I'll even donate a small amount of cryptocoins on success.

Except of sha256 and with stratum support.

**Comment by luke-jr** [comment]
There's libblkmaker...

**Comment by Gargo** [comment]
Sorry, but I forgot to mention - except of sha256 and with stratum support.
Could it be made from bfgminer sources or something similar?

**Comment by luke-jr** [comment]
I don't see the point.

**Comment by Gargo** [comment]
Look deeper. This idea increases the sphere of application of bfgminer.
For example, I want to create a online game where people. I want to allow people to choose to donate  real money or to earn additional game money via cryptocoins. And I want to call miner inside my game but it is hard for me to add miner software inside the game.

**Comment by luke-jr** [comment]
Can't you just execute BFGMiner and access it via RPC?

**Comment by Gargo** [comment]
you mean an additional separate window of bfg miner. I want to build it into a game. I want not only control but get results of miner (callback).

**Comment by luke-jr** [comment]
This doesn't make sense. Run it without a window...

**Comment by Quix0r** [comment]
And you can always use "screen -dmS bfgminer" (example) to "daemonize" it. :)

**Comment by Gargo** [comment]
if you don't know "screen" is for linux only. I need to run it in windows

**Comment by nwoolls** [comment]
If you can write a computer game, you can run a program without its window being shown.
