### ISSUE TITLE
Version reported incorrectly to API "version" command. 

### ISSUE THREAD

**Issue by starlilyth** [luke-jr/bfgminer#435]
The "version" API command returns the incorrect information in REPLY. 
For example: 
STATUS=S,When=1398287656,Code=22,Msg=BFGMiner versions,Description=bfgminer 3.99.0|VERSION,CGMiner=3.99.0,API=3.1|

While the description in the STATUS reply is correct, the REPLY to the command is not (REPLY is this part: |VERSION,CGMiner=3.99.0,API=3.1|)

"version" REPLY should report the same information as is reported in the STATUS section. Any application using the "version" command will expect the REPLY value to contain the requested data.

**Comment by luke-jr** [comment]
This works as intended. Applications should not expect the key to change based on the application name; that is what the Description field is intended for.

**Comment by starlilyth** [comment]
Your application will be reported as CGMiner to all applications that use the API properly.

**Comment by luke-jr** [comment]
improperly*

**Comment by luke-jr** [comment]
How about adding a separate SoftwareName key, if you don't like Description?

**Comment by starlilyth** [comment]
The format of each reply (unless stated otherwise) is a STATUS section
followed by an optional detail section

The STATUS section is:
STATUS=X,When=NNN,Code=N,Msg=string,Description=string|
...
Description=string
This defaults to the cgminer version
...
The list of requests and replies:
 Request Reply Section Details
 version VERSION CGMiner=cgminer, version
                              API=API| version

https://github.com/ckolivas/cgminer/blob/3.7/API-README

Please refer to the SGMiner code where this is reported correctly. 

STATUS=S,When=1398287596,Code=22,Msg=SGMiner versions,Description=sgminer 4.1.271|VERSION,SGMiner=4.1.271,API=3.2

**Comment by luke-jr** [comment]
As your API-README link says (as well as the [BFGMiner README.RPC](https://github.com/luke-jr/bfgminer/blob/bfgminer/README.RPC#L149)), the "CGMiner" key is used to report the software version.

SGMiner is using a different key, which is not compatible with the traditional RPC interface that BFGMiner and cgminer have been using for years.

**Comment by starlilyth** [comment]
Its your problem, not mine. When people ask me why the version is reported incorrectly in my application, I will refer to this thread. 

Your application is not "CGMiner". It should not say it is.

**Comment by luke-jr** [comment]
It doesn't say it is. "CGMiner" just happens to be the key used for the version number, in a key/value pair, due to legacy reasons. If your software treats it as a value (which it isn't; it's a key), that's a bug in your software... If you want another key to report the software name, I can certainly add that.

**Comment by starlilyth** [comment]
" CGMiner=cgminer, version"

Your output should be "CGMiner=BFGMiner,3.99.0"

No?

**Comment by starlilyth** [comment]
I agree now, SGMiner is doin it wrong. You are right, CGMiner= is a key, BUT

"CGMiner=cgminer, version"

So: 
"CGMiner=BFGMiner,3.99.0"
"CGMiner=SGMiner,4.1.271"
"CGMiner=CGMiner,3.7.2"
Are the correct formats.

**Comment by luke-jr** [comment]
If we were enforcing cgminer's API-README, you may have an argument there. But neither BFGMiner nor cgminer have ever used that format. Maybe adding Software=BFGMiner,3.99.0 would be satisfactory?

**Comment by starlilyth** [comment]
Maybe adhering to the format that has long been documented and will be referred to anyway would be best. I will open an Issue with SGMiner as well.

**Comment by luke-jr** [comment]
The primary goal of the CGMiner key, at this point, is for backward compatibility with software that's been used for years now. If we're going to fix the format, we should just go ahead and fix the key name to be less confusing at the same time.

**Comment by starlilyth** [comment]
If you are going to force all application producers to do something different, it may as well be towards compliance with pre-existing formatting, even if it has never been complied with before, and not new variables that will not be replicated in all forks. IMHO

**Comment by luke-jr** [comment]
Adding a new key doesn't force anyone to change things.

**Comment by starlilyth** [comment]
Not if they want to ignore their users, no. New anything generates feature requests, as I am sure you are aware. Since you have the leverage to dictate the outcome of the solution regardless of any input I or anyone else provides, I guess we are stuck with whatever you want. 

A new key in the REPLY to "version", such as "Software=BFGMiner,3.99.0 " sounds reasonable.

**Comment by starlilyth** [comment]
My current solution is this: Miner=(\w+,)?(\d+.\d+.\d+). If no Miner name is reported per the documented spec, it defaults to CGMiner. 

If you decide to add another key, and it is adopted by cgminer or other major forks, then I may use it.

**Comment by luke-jr** [comment]
I was thinking that'd work well with:

```
STATUS=S,When=1398287656,Code=22,Msg=BFGMiner versions,Description=bfgminer 3.99.0|VERSION,Miner=BFGMiner,3.99.0,CGMiner=3.99.0,API=3.1|
```

But then I realised , is used as the separator between key/value pairs... :/
