### ISSUE TITLE
Incomplete response to API "version" command.

### ISSUE THREAD

**Issue by starlilyth** [luke-jr/bfgminer#436]
Per the API documentation:
"CGMiner=cgminer, version"

So:
"CGMiner=BFGMiner,3.99.0,"
Is the expected output.

"CGMiner=3.99.0,"
is the actual output.

**Comment by luke-jr** [comment]
README.RPC:

```
 Request       Reply Section  Details
 -------       -------------  -------
 version       VERSION        CGMiner=BFGMiner version
                              API=API version
```

Will adding "Miner=BFGMiner\,3.99.0,..." work for you?

**Comment by starlilyth** [comment]
Sounds ideal. A whitespace would be perfectly acceptable as well, as the comma is a separator, as you noted.

**Comment by starlilyth** [comment]
After a brief discussion with kanno, the miner name apparently isnt meant to be reported, and he could care less how anyone feels about it, so apparently I am the only one. 

Feel free to ignore this non-issue.

**Comment by luke-jr** [comment]
Well, I see why you'd want the software name in there too. If "Miner=BFGMiner 3.99.0" is your ideal format, I'm fine with adding that.

**Comment by starlilyth** [comment]
Please dont. 

All I want is for forks to follow a standard, which they currently do, even if it is programatically wrong.  I should never have to gather REPLY data from STATUS, but that currently the only reliable way ALL forks report their name. 

I fault the cgminer API author for failing to name keys sensibly, write documentation clearly, or provide obviously needed data from the beginning.

**Comment by luke-jr** [comment]
There's no reason to limit ourselves to the original RPC interface, given that the author (Kano) is now working on a fork (cgminer). I'll discuss the idea with @veox and maybe we can at least get a standard between BFGMiner and SGMiner.

**Comment by starlilyth** [comment]
Good luck with that. https://github.com/sgminer-dev/sgminer/issues/199#issuecomment-41304324

I would love to see a proper reply to 'version' that had "Name=, Version=, API=" in the response from all forks, but I have low hope for ever seeing this.

**Comment by veox** [comment]
I don't have a strong opinion on this. `"Miner=<name> <version>"` sounds perfectly fine, just as making sgminer's behaviour same as cgminer/bfgminer, or adding `"Name=<name>"` and `"Version=<version>"`...

**Comment by starlilyth** [comment]
IMHO `Miner=<name> <version>` sounds easier to implement across all forks, least likely to break legacy apps in a bad way, and trivial to accommodate in currently produced apps.

**Comment by luke-jr** [comment]
@starlilyth @veox Please review #437

**Comment by starlilyth** [comment]
Looks great to me

**Comment by veox** [comment]
Looks just fine. Cherry-picking and merging.

**Comment by veox** [comment]
P.S. I'll also revert the "SGMiner" back to "CGMiner". Sorry for the noise.
