### ISSUE TITLE
Stratum-Proxy eats up all memory (malloc-problem?)

### ISSUE THREAD

**Issue by toms001** [luke-jr/bfgminer#443]
When i run a miner with

./bfgminer -o stratum+tcp://stratum.btcguild.com:3333 -u XXXXX -p 123 -S all --icarus-options 115200:1:1 --icarus-timing 3.0=100 --http-port 8330 --socks-proxy 192.168.1.102

the memory-usage is constant, but when i start a miner with a stratum-proxy it eats up all memory in about 1 or 2 days and quits:

./bfgminer2 -o stratum+tcp://stratum.btcguild.com:3333 -u XXXXX -p 123 --stratum-port 8331 --socks-proxy 192.168.1.102

i'm using the latest git.

**Comment by luke-jr** [comment]
Fixed in f8002e6, thanks!
