### ISSUE TITLE
Repeatedly declared unrecoverably SICK, while 60 sec idle

### ISSUE THREAD

**Issue by leder11011** [luke-jr/bfgminer#446]
Hello and thanks for the best known GPU scrypt miner on Ubuntu 14.04! Using AMD ATI Radeon R9 290X.

Can you please make it more robust for open cl mining? Either by recovering after declaring it sick or not declaring it sick too easily? Bye Gerrit

![bildschirmfoto vom 2014-05-11 19 20 35](https://cloud.githubusercontent.com/assets/3330116/2939042/5e9800e4-d933-11e3-95a0-3463036f386a.png)

**Comment by luke-jr** [comment]
It already does everything possible to recover.
