### ISSUE TITLE
Issues running DualMiner, AntMiner U2 and Erupter simultaneously 

### ISSUE THREAD

**Issue by mdehaas** [luke-jr/bfgminer#448]
I have an issue running the DualMiner (DMU) alongside the ICA and AMU devices. ICA and AMU are playing along, both mining Zetacoin. When I start the dualminer for a scrypt algo (DOGE) the devices start dropping to OFF and Windows plays the nice USB plugout/plugin sounds. I've tried fixing the COM ports to scan but that resulted in no found devices.
Is this scenario even possible, if you don't see why not what can I do to troubleshoot the issue? I'm running a self compiled version which did not give me any issues until I got a DualMiner...

Thanks in advance.
Kind regards
Marcel

**Comment by luke-jr** [comment]
Sounds like a USB power issue...

**Comment by mdehaas** [comment]
I didn't expect that when using an external powered USB HUB, but it seems that way. The problems can be reproduced when I plug in an external USB HD. The problem seem to get worse, Now also the ICA and AMU alone have the issue. I think the HUB is dying. Thanks for the help.
