### ISSUE TITLE
Saner defaults?

### ISSUE THREAD

**Issue by OhGodAPet** [luke-jr/bfgminer#449]
I understand why support for most miners is automatically enabled with configure - because this way, users who don't know what type of driver they need can just use the defaults, and most of the time it'll just work.

However, why are libmicrohttpd and libevent enabled by default? If I'm understanding their purpose correctly, they provide support for bfgminer to run a getwork and stratum server on the local machine, respectively. Most users who don't know how to use configure options aren't even going to know bfgminer can do that, let alone actually use the features.

**Comment by luke-jr** [comment]
It's mostly harmless to compile them (just another few seconds of build time on most machines). I think you may underestimate how common they are, also. Users who want to build only select drivers can use the new --disable-other-drivers option.
