### ISSUE TITLE
API - Dead erupter, hashrate remains.

### ISSUE THREAD

**Issue by njdro** [luke-jr/bfgminer#452]
I use a script to output my hashrate using bfgminer's API;  If a USB erupter dies or is otherwise unresponsive, the hashrate is not zero'd, therfore the API still reports a hashrate including the last good rate of the dead erupter. (which is obviously wrong)

**Comment by luke-jr** [comment]
This is a protocol design flaw for icarus-based devices. "Not responding" is what it normally looks like when it's mining. :(

**Comment by njdro** [comment]
maybe i should not have used the terminology "not responding"...  i mean if one dies, stops working, or is unplugged.  i'd like the API to report accurate stats.
