### ISSUE TITLE
bfgminer build issue (git: command not found)

### ISSUE THREAD

**Issue by sgtditty** [luke-jr/bfgminer#458]
I get to the point where I'm told to enter "git clone git://github.com/luke-jr/bfgminer.git" into MinGWshell and I get the error "sh: git: command not found". I have followed the windows-build file to the letter. Should I start over or is there something else I should try first. Any help would be great.
![capture123](https://cloud.githubusercontent.com/assets/7751905/3138165/41b7acee-e875-11e3-9df4-6d5daf3dffd7.PNG)

Thanks,
SgtDitty

**Comment by nwoolls** [comment]
Check step *\* Configure Git in MinGW *\* and make sure that the path you are entering for Git matches the path on your Windows build system. It may be different for x64 systems. Unfortunately this is not currently called out in the Windows build documentation.

**Comment by nwoolls** [comment]
Please feel free to reopen if you are still having trouble compiling BFGMiner for Windows.
