### ISSUE TITLE
Scrypt stratum proxy difficulty

### ISSUE THREAD

**Issue by Blaater** [luke-jr/bfgminer#466]
Hi,

There is a similar issue with a fix for SHA-256 (https://github.com/luke-jr/bfgminer/pull/456), but for scrypt there should be one aswell.

Could you please increase the standard difficulty in the next BFGMiner release, my 150 mh/s miner is showing a speed of 1 mh/s cause of this low difficulty it is receiving for speedtest.

Best regards and keep up the work.

**Comment by luke-jr** [comment]
Please help test and review #486
