### ISSUE TITLE
static declaration of ‘opt_set_floatval’ follows non-static declaration

### ISSUE THREAD

**Issue by Quix0r** [luke-jr/bfgminer#475]
## I get this with latest 'bfgminer' branch:

  CC       bfgminer-miner.o
distcc[30634] ERROR: compile miner.c on 192.168.2.3 failed
distcc[30634](dcc_build_somewhere) Warning: remote compilation of 'miner.c' failed, retrying locally
distcc[30634] Warning: failed to distribute miner.c to 192.168.2.3, running locally instead
miner.c:1139:7: error: static declaration of ‘opt_set_floatval’ follows non-static declaration
In file included from miner.c:63:0:
./ccan-upstream/ccan/opt/opt.h:413:7: note: previous declaration of ‘opt_set_floatval’ was here
miner.c:1153:6: error: static declaration of ‘opt_show_floatval’ follows non-static declaration
In file included from miner.c:63:0:
./ccan-upstream/ccan/opt/opt.h:414:6: note: previous declaration of ‘opt_show_floatval’ was here
distcc[30634] ERROR: compile miner.c on localhost failed
make[2]: **\* [bfgminer-miner.o] Error 1
make[2]: Leaving directory `/home/quix0r/git/bfgminer'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/quix0r/git/bfgminer'
## make: **\* [all] Error 2

gcc version 4.7.3 (Debian 4.7.3-11)

**Comment by luke-jr** [comment]
Sounds like you updated ccan-upstream to a newer version that isn't (yet) supported.

**Comment by Quix0r** [comment]
It is building now again. You may close this. :)
