### ISSUE TITLE
bifury: Bug: only produces invalid nonces on Big Endian HW

### ISSUE THREAD

**Issue by nwoolls** [luke-jr/bfgminer#479]

**Comment by luke-jr** [comment]
Fixed in bbaf5fa

**Comment by nwoolls** [comment]
Still getting only HW errors (invalid nonce) on BE HW.

**Comment by luke-jr** [comment]
Must be power or cooling? bbaf5fa fixed it for me... :/

**Comment by nwoolls** [comment]
Thanks - working now after shuffling USB hubs. Good to go.
