### ISSUE TITLE
Overclock not setting frequency?

### ISSUE THREAD

**Issue by 9600-** [luke-jr/bfgminer#499]
It seems that no matter what --set rockminer:clock= is set to, the unit will always hash 32GH. Never more, lever less.

**Comment by nwoolls** [comment]
If I run it at 290 I get a little over 34 Gh/s, but it takes a few hours for things to play out:

34.65/34.01/33.70

From talking to Luke these things are clocked pretty much as fast as they'll go.

**Comment by 9600-** [comment]
Thanks for the fast reply. Glad to hear your results are close to mine. The only reason I raised the flag was the RBox cgminer build was supplying between 33-35 while BFGMiner was only showing about 32 locally. I never let the unit run for more than 15 minutes though.

Would much rather use BFGMiner as their CGMiner is missing RPC API data!

**Comment by luke-jr** [comment]
If you compare actual pool-side results, you will notice that the cgminer is simply misreporting/lying about the hashrate. They both perform approximately the same.
