### ISSUE TITLE
Hold gridseed  G-Blade after correction (Reduce traffic sending work to GridSeed )devices)

### ISSUE THREAD

**Issue by gades** [luke-jr/bfgminer#501]
About a day the device stops to issue decisions. Reset bfgminr'a solves this problem. May need a timer from the last decision and sending reset to device?

![2014-07-12 11 02 49](https://cloud.githubusercontent.com/assets/4200730/3560937/cb5cc3d4-099b-11e4-980e-60205aae57de.png)

**Comment by nwoolls** [comment]
This is something we plan to address by improving the watchdog functionality in BFGMiner.

**Comment by gades** [comment]
Fix in commit 7b2613ec3a4908c9e5d70f2fbe57635ad62c6da4
