### ISSUE TITLE
Bug Proxy-stratum server: Binary data send to stratum server and not in plain text data

### ISSUE THREAD

**Issue by evolvia31** [luke-jr/bfgminer#542]
Hi,  I try to use bfgminer with this stratum proxy server (https://github.com/Stratehm/stratum-proxy) and i have a big problem.
When i configure bfgminer to connect on it i have this message error:

2014-08-19 07:47:59,533 ERROR [/192.168.0.39:41000-Thread]: [WorkerConnection]
Parsing error on worker connection /192.168.0.39:41000. Failed to parse line ^V^C^A^@�^A^@^@�^C^BS��^^�t���^K Qk^W^H���^X~ $�?4z��^@^@f�^T�.
com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 22)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: ^V^C^A^@�^A^@^@�^C^BS��^^�t���^K Qk^W^H���^X~ $�?4z��^@^@f�^T�; line: 1, column: 2]

When i use it with cgminer or sgminer all works weel.

With bfgminer, data are sent in binary mode or crypted, i don't know why bfgminer don't send data in plain text or if there are an option in bfgminer to send it in plain text.

My config file is:
{
"pools" : [
        {
                "name" : "test",
                "url" : "stratum+tcp://192.168.0.45:4333",
                "user" : "gsd1",
                "pass" : "x"
        }
],
"api-mcast-port" : "4038",
"api-port" : "4038",
"api-listen" : true,
"api-allow" : "W:192.168.0.45",
"expiry" : "10",
"hotplug" : "15",
"log" : "60",
"no-pool-disable" : true,
"queue" : "0",
"scan-time" : "3",
"scrypt" : true,
"shares" : "0",
"kernel-path" : "/home/bfgminer/bfgminer/opencl",
"scan" : [
        "gridseed:all"
],
"set-device" : [
        "gridseed:clock=800,chips=40"
]
}

Thank you to your help.

PS: I contact the owner of stratum-proxy and for him problem is in bfgminer not in this proxy-stratum.
Maybe an option to send data in plain text.

**Comment by luke-jr** [comment]
BFGMiner will retry without encryption if TLS fails. Perhaps his proxy is failing to disconnect it in a timely manner?

You can skip the TLS entirely by adding #notls to the pool URI.
