### ISSUE TITLE
CPU mining doesn't mine

### ISSUE THREAD

**Issue by smurfix** [luke-jr/bfgminer#543]
I did this (current git master, Debian wheezy):

```
 ./configure --enable-scrypt --enable-cpumining --disable-opencl  --disable-other-drivers
make
./bfgminer --cpu-threads 24 --scrypt --show-processors -T -D
[…]
[2014-08-20 04:34:25] No devices detected!
[2014-08-20 04:34:25] Waiting for devices
[…]
[2014-08-20 04:34:28] 24 cpu miner threads started, using 'scrypt' algorithm.
```

However, bfgminer merely spawns four threads, not 24 (checked with `pstree`), none of which does anything:

```
20s:  0.0 avg:  0.0 u:  0.0  h/s | A:0 R:0+0(none) HW:0/none
```

**Comment by smurfix** [comment]
Found it: Option `-S cpu:auto` needs to be added. This should happen automatically when using the `cpu-threads`option.

**Comment by luke-jr** [comment]
@smurfix Patches welcome

**Comment by luke-jr** [comment]
IMO ideally --cpu-threads should be removed entirely and -S cpu:N replace it.
