### ISSUE TITLE
bfgminer 4.7.0-13-g9d393ec double-free malloc error

### ISSUE THREAD

**Issue by silverdr** [luke-jr/bfgminer#545]
I am not sure if this is a known problem but what I got after having bfgminer run for a while is:

bfgminer(47513,0x1108b1000) malloc: **\* error for object 0x7fc891602270: double free-------------------------------------------
                                     **\* set a breakpoint in malloc_error_break to debug8-23 01:53:22] Longpoll from pool 1 detected new block
        Abort trap: 6

**Comment by luke-jr** [comment]
Can you run it in valgrind? What drivers? How about gdb with a breakpoint on malloc_error_break as it suggested?

**Comment by silverdr** [comment]
Only bifury (-S bifury:all) ASICs. It's an OSX 10.9.x machine so valgrind is probably not an option. I am unfortunately not an expert on gdb either. I may try to run it within "Instruments" if that can help. Or if you guide me through I can set things up with gdb.

**Comment by luke-jr** [comment]
How long do you need to run it?

**Comment by luke-jr** [comment]
I have not been able to reproduce any issues after over 24 hours of running the current code on my bi*fury. Anything else unusual/configured about your configuration?

**Comment by silverdr** [comment]
Maybe it is OSX specific. Did you run it on OSX 10.9.4? I don't think there is anything unusual in the config. Maybe you can have a look here:

silverdr$ cat .bfgminer/bfgminer.conf 
{
"pools" : [
    {
        "url" : "127.0.0.1:8332",
        "user" : "secret",
        "pass" : "secret",
        "coinbase-addr" : "secret",
        "coinbase-sig" : "Silver Dream !",
        "pool-priority" : "0"
    },
    {
        "url" : "api.polmine.pl:8347",
        "user" : "silverdr261880",
        "pass" : "0",
                "coinbase-addr" : "secret",
                "coinbase-sig" : "Silver Dream !",
        "pool-priority" : "0"
    }
]
,
"api-mcast-port" : "4028",
"api-port" : "4028",
"expiry" : "120",
"expiry-lp" : "3600",
"failover-only" : true,
"failover-switch-delay" : "300",
"log" : "5",
"no-pool-disable" : true,
"no-client-reconnect" : true,
"no-show-processors" : true,
"no-show-procs" : true,
"queue" : "1",
"quiet-work-updates" : true,
"quiet-work-update" : true,
"scan-time" : "60",
"skip-security-checks" : "0",
"submit-stale" : true,
"temp-hysteresis" : "3",
"shares" : 0,
"kernel-path" : "/usr/local/share/bfgminer",
"scan" : [
    "bifury:all"
],
"api-allow" : "W:127.0.0.1,W:192.168.0/24"
}

**Comment by silverdr** [comment]
I noticed I somehow didn't answer your question about the time? Maybe I didn't submit it.. strange. Anyway, I compiled it fresh, started, it ran for a few hours and then I went to sleep. In the morning it was already crashed. Logs at the pool (not highly accurate but good estimation) show that it ran for about two hours more. In total that would make probably about five hours before the crash.

**Comment by luke-jr** [comment]
This kind of issue wouldn't usually be OS-specific, but no, I don't use Mac at all...

**Comment by silverdr** [comment]
I agree - malloc stuff is rarely platform specific. I can give it another run tonight. If you like me to set it with anything gdb or something that would help tracking the problem down, please let me know. I'll start it within time command and then can post the output back. Regards.

**Comment by luke-jr** [comment]
I'd suggest trying the gdb breakpoint the error mentioned.

**Comment by nwoolls** [comment]
FYI not able to reproduce this myself on Mac OS X:

![](http://www.nwoolls.com/othercontent/HexFury%20-%209%20Hours.png)

**Comment by silverdr** [comment]
You seem to run a slightly different version but it's probably one of those "esoteric" problems anyway.. I run the same binary for two days now and it doesn't pop-up again so far.

**Comment by silverdr** [comment]
It seems not to show anymore. While I don't like this kind of problems to "get fixed by themselves", I tried long enough and I don't think it adds value to keep this issue open any longer. Closing.

**Comment by luke-jr** [comment]
It's possible it was fixed without realising it was the cause of your crash.
