### ISSUE TITLE
BFGMiner 4.8 crashes on Windows scanning for hardware

### ISSUE THREAD

**Issue by nwoolls** [luke-jr/bfgminer#557]
Seems to be related to the Cointerra driver.

bfgminer -d? -S all

Failed to init bfd from (C:\Users\Nathanial\Documents\Mining\MultiMiner\Miners\B
FGMiner\libusb-1.0.dll)
0x6b602094 : C:\Users\Nathanial\Documents\Mining\MultiMiner\Miners\BFGMiner\libu
sb-1.0.dll : libusb_open
0x4abc86 : C:\Users\Nathanial\Documents\Mining\MultiMiner\Miners\BFGMiner\bfgmin
er.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tm
p/bfgminer-4.8.0-tmp/bfgminer-4.8.0/driver-cointerra.c (283) : in function (coin
terra_lowl_probe)
0x42b2bf : C:\Users\Nathanial\Documents\Mining\MultiMiner\Miners\BFGMiner\bfgmin
er.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tm
p/bfgminer-4.8.0-tmp/bfgminer-4.8.0/miner.c (11916) : in function (_probe_device
_do_probe)
0x42b831 : C:\Users\Nathanial\Documents\Mining\MultiMiner\Miners\BFGMiner\bfgmin
er.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tm
p/bfgminer-4.8.0-tmp/bfgminer-4.8.0/miner.c (12054) : in function (probe_device_
thread)
Failed to init bfd from (C:\Users\Nathanial\Documents\Mining\MultiMiner\Miners\B
FGMiner\pthreadGC2.dll)
0x6248671b : C:\Users\Nathanial\Documents\Mining\MultiMiner\Miners\BFGMiner\pthr
eadGC2.dll : pthread_create
Failed to init bfd from (C:\Windows\SYSTEM32\msvcrt.dll)
0x777d0bc4 : C:\Windows\SYSTEM32\msvcrt.dll : wtoi64
Failed to init bfd from (C:\Windows\SYSTEM32\msvcrt.dll)
0x777d0cec : C:\Windows\SYSTEM32\msvcrt.dll : beginthreadex
Failed to init bfd from (C:\Windows\SYSTEM32\KERNEL32.DLL)
0x7768495d : C:\Windows\SYSTEM32\KERNEL32.DLL : BaseThreadInitThunk
Failed to init bfd from (C:\Windows\SYSTEM32\ntdll.dll)
0x77db98ee : C:\Windows\SYSTEM32\ntdll.dll : RtlInitializeExceptionChain
Failed to init bfd from (C:\Windows\SYSTEM32\ntdll.dll)
0x77db98c4 : C:\Windows\SYSTEM32\ntdll.dll : RtlInitializeExceptionChain

**Comment by luke-jr** [comment]
Fixed in 2d19cdb
