### ISSUE TITLE
Can’t see Nano Fury NF2 

### ISSUE THREAD

**Issue by lextad** [luke-jr/bfgminer#559]
hello i have a Problem my nanofury nf2 are no way to be found  with MM, but if i run BFG 3.1/4.7/4.8 they are found with out any problems. MM found the rest of the USB Miners U1/U2/R-box 
Thanks in advance 
![capture](https://cloud.githubusercontent.com/assets/8764151/4267087/620b5574-3c92-11e4-83ff-ab8524451409.PNG)

**Comment by nwoolls** [comment]
For scanning hardware with MultiMiner (including troubleshooting), see the following:

https://github.com/nwoolls/MultiMiner/wiki/Local-Devices

Also note that this is the repository specifically for BFGMiner, if the issue is with MultiMiner please use:

http://issues.multiminerapp.com

Thanks!
