### ISSUE TITLE
scrypt pool share difficulty display

### ISSUE THREAD

**Issue by beht** [luke-jr/bfgminer#560]
there seems to be an inconsistency regarding the share difficulty display,to be more specific, the pool in question (coinotron) requests a share difficulty of 1400 mining litecoin, but bfgminer reports a share difficulty of 21m. when mining solo, bfgminer reports the the share difficulty to be the same as the network difficulty which I think is correct. but in case of any scaling happening for the pool difficulty, isn't it affecting the target difficulty calculation while mining solo?
another issue is the income report while mining litecoin. how should the value reported in btc/hr be converted to ltc/hr?

**Comment by nwoolls** [comment]
Many pool implementations use a multiplier internally for Scrypt difficulty - some do not. No multiplier is used with SHA2 pools.

While this multiplier has become common, the author(s) of BFGMiner feel it is an unnecessary addition / overhead. BFGMiner will automatically detect pool implementations that use this multiplier and "undo" the multiplier internally. That is why you see a different value displayed on screen.

None of this should / would affect performance.

**Comment by beht** [comment]
Dear Nate;
 Could you please tell me if the Best Share reported by BFGMiner in this
case is also normalized the same way?

**Comment by luke-jr** [comment]
BFGMiner always measures difficulty by the standard definition. ie, not whatever re-definition altcoins use these days.
