### ISSUE TITLE
can't run "make" command

### ISSUE THREAD

**Issue by Carlgo11** [luke-jr/bfgminer#566]
I just installed bfgminer or at least I tried to.
I did: 
`git clone https://github.com/luke-jr/bfgminer.git`
`./autogen.sh`
`make`  
but when I do `make` I get `make: *** No targets specified and no makefile found.  Stop.`
I'm in the same dir so it shouldn't output that. What do I do?

**Comment by luke-jr** [comment]
README, or even following standard build instructions...
