### ISSUE TITLE
startup of miner with target diff 0 causing "Share above target"

### ISSUE THREAD

**Issue by Quix0r** [luke-jr/bfgminer#574]
The said message comes very often, after ~5-10 seconds, the difficulty from the pool is taken

> [2014-11-06 01:48:06] Rejected 8a29991a RKM 0c Diff 1/0 (Share above target)
> [2014-11-06 01:48:06] Rejected 962bf057 RKM 0a Diff 1/0 (Share above target)

Then it switches to pool diff and the message is gone:

> [2014-11-06 01:48:34] Rejected d0d16e23 RKM 0b Diff 1/0 (Share above target)
> [2014-11-06 01:48:42] Accepted 04b7d755 RKM 0a Diff 54/31
> [2014-11-06 01:48:44] Accepted 0454ef2f RKM 0c Diff 59/31

BFGMiner: 4.10.0-44 (master).

**Comment by luke-jr** [comment]
What server is this? Diff 0 is ... not something RockMiners support.

**Comment by Quix0r** [comment]
Sorry for super-long delay of my answer, I lost track on this issue ... :-/

It was stratum.d7.lt.

**Comment by luke-jr** [comment]
Does this still affect 5.2?

**Comment by luke-jr** [comment]
Looks like this is a pool issue. It's not setting any difficulty until after a share is submitted.
