### ISSUE TITLE
 ASIC Block Erupter USB 330MH/s for Vanity Address Gen?

### ISSUE THREAD

**Issue by ShaliDaliHaliDa** [luke-jr/bfgminer#585]
Hi,
I have an older ASIC Block Erupter USB 330MH/s which is now pretty useless for mining. However, since it's really good at hashing I am wondering if I could mod / use it to generate faster bitcoin vanity addresses? My home CPU is too slow, would be cool if I could sue it for something. Any ideas?

**Comment by luke-jr** [comment]
No, ASICs only do what they're designed to do and nothing else.

**Comment by ShaliDaliHaliDa** [comment]
Cool. So it's a paperweight? Aren;t they designed to SHA256 really quickly?

**Comment by luke-jr** [comment]
They're designed to SHA256d and return results that have the final 32 bits zero. Address generation, on the other hand, has absolutely nothing in common with this, and mostly consists of ECDSA and Base58 encoding.

**Comment by ShaliDaliHaliDa** [comment]
Appreciate the answer. Any suggestions what I can do with my 330MH/s USB miners?

**Comment by luke-jr** [comment]
I hear people are making fashon pins out of them. Another option is to keep mining with them for the benefit of the network (at little cost to yourself per unit), or pass them on to someone who will.
