### ISSUE TITLE
bfgminer-4.99.1-68-gd907e24 - gridseed never fiinishes initialising

### ISSUE THREAD

**Issue by minusbat** [luke-jr/bfgminer#588]
Am trying the latest bfgminer, following the fix for the mutex issue (thanks or that!). I have a single gridseed orb which works fine in bfgminer-4.9.0-20-gadc766b, and have configured the new bfgminer the same way. When I run it I give is the device for the gridseed, it detects it, but from then onwards it
always reports

GSD 0: Initializing...

and never leaves that state. There are very few differences between the gridseed driver in this version and the working version, but the change which is there is the removal of an initialisation function which was allocating a block of data in the older version of the driver. What can I do to help debug this ?

**Comment by luke-jr** [comment]
Commandline and/or config files in use would be helpful

**Comment by minusbat** [comment]
Command line is this:
./bfgminer --scrypt -o stratum+tcp://cesc.plentygadget.pt:3333 -u pestpool.skerrycpu -p skp112

I am adding the gridseed using M+ in the user interface - the device is on /dev/cuaU0. I alwasy need to try a few times before it is recognised. On 4.9 it then ijtialises and lets me set the clock speed to 850, on 4.99 it never leaves the Initialising state.

My configure line looks like this if it matters...
./configure \
        CC="gcc48" \
        CXX=g++48 \
        AS=/usr/local/bin/as \
        LD=/usr/local/bin/ld \
        SHELL=/usr/local/bin/bash \
        CFLAGS="-pthread -I/usr/local/include -march=native -O3" \
        CXXFLAGS="-pthread -I/usr/local/include -march=native -O3" \
        LDFLAGS="-pthread -L//usr/local/lib/gcc48" \
        --without-vfio \
        --without-uio \
        --without-libusb \
        --disable-other-drivers \
        --enable-scrypt \
        --enable-gridseed

**Comment by luke-jr** [comment]
Please let me know if this is resolved by 42d62f7 (in the main git branch).

**Comment by minusbat** [comment]
yes, that commit fixes it, thanks.
