### ISSUE TITLE
BitFORCE throttling can take some time to respond

### ISSUE THREAD

**Issue by luke-jr** [luke-jr/bfgminer#59]
Kano added a ridiculous 0.1s timeout to BFL reads, which obviously breaks easily. Increased this to 1s in git, but probably not enough.

Proposed logic:
- For detect, 1s timeout
- For mining, 30s timeout

Question: Is there any case where the MCU won't respond, even delayed?

**Comment by luke-jr** [comment]
Fixed in 07b6133

**Comment by kanoi** [comment]
"Kano added a ridiculous 0.1s timeout to BFL reads, which obviously breaks easily."

Whenever you don't specify bitforce: for a BFL, with cgminer code that has both ICA and BFL, it already set bitforce timeout to 0.1s by your original code change to check icarus before bitforce months ago and not set a timeout with bitforce ... so I guess when you implemented that "ridiculous", "obvious" break you were purposefully causing problems for people using your miner ...

(or your comment is bullshit as usual)

Also, BFL-Engineer stated that requesting the Temp during a throttle works without delay
https://bitcointalk.org/index.php?topic=78256.msg885143#msg885143
though comments from BFL are probably as unreliable as your comments ...

**Comment by luke-jr** [comment]
@kanoi While it is true that it inherited the timeout from Icarus with an all-FPGA scan-serial on Linux (and that was a bug), on Windows it had set a 30 second timeout. On Linux, there was no reason to ever use scan-serial with BitFORCE since it could autodetect, so in practice the 0.1s timeout never really hit anyone.
