### ISSUE TITLE
libncurses-dev and ./config error

### ISSUE THREAD

**Issue by dowsettmark** [luke-jr/bfgminer#606]
Hi,
-you are dealing with a bit of a noob here:
build on RPi-Raspbian

I ran into errors installing libncurses-dev last night and when trying to run ./configure - "command not recognized"

More than likely its me, but I noticed the latest commit on the config file was 15hrs ago (at time of attempt)?

**Comment by luke-jr** [comment]
Just install it from aptitude... this isn't related to BFGMiner from what you've said.

**Comment by dowsettmark** [comment]
Ok, sorry for the time waste.

So run: sudo aptitude bfgminer

**Comment by dowsettmark** [comment]
Sudo aptitude install bfgminer

**Comment by luke-jr** [comment]
from README...

sudo aptitude install build-essential autoconf automake libtool pkg-config libcurl4-gnutls-dev libjansson-dev uthash-dev libncursesw5-dev libudev-dev libusb-1.0-0-dev libevent-dev libmicrohttpd-dev

Then follow the other instructions in README to compile.
