### ISSUE TITLE
[W64]Ring 0 instead User-mode ?

### ISSUE THREAD

**Issue by Pascal66** [luke-jr/bfgminer#607]

**Comment by luke-jr** [comment]
What?

**Comment by Pascal66** [comment]
I Windows, miner stop to work when swtiching user or session lock.
Because of drivers working in user mode
Is thre a way to made driver worlking in rng0 mode to avoid that ?

**Comment by luke-jr** [comment]
This has nothing to do with ring 0.

**Comment by Pascal66** [comment]
I trust, you. was just thinking that video drivers works in ring 3 in windows
And was thinking that is just why when i put a password in my session, 
all driver in ring 3 stopped to work, ie gpu usage
