### ISSUE TITLE
--sched-stop unexpected behavior

### ISSUE THREAD

**Issue by blinkier** [luke-jr/bfgminer#61]
Using --sched-stop with a time that has already passed in the current day causes bfgminer to terminate immediately.
For example, if it's 21:00 and bfgminer is run with --sched-stop 7:00, it will terminate immediately.
If it's 21:00 and bfgminer is run with --sched-stop 21:01, it will terminate after one minute.

However, if I run bfgminer with --sched-start 21:00 --sched-stop 7:00, I get a somewhat expected result (starts mining immediately and quits mining at 7:00 but does NOT terminate.)

**Comment by luke-jr** [comment]
Fixed in ece3f20
