### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by drewkoz** [luke-jr/bfgminer#616]
I have an AMD R7 GPU. I'm running kubuntu 15:04. I have the proprietery AMD drivers installed. Yet whenever I run bfgminer I just get "No Device Found" Any suggestions?

**Comment by luke-jr** [comment]
This is following the instructions in README.GPU? Particularly the -S opencl:auto option?

**Comment by drewkoz** [comment]
Yes. Actually I did solve this by doing a force install of AMD catalyst drivers. Now I can use the m+ (I'm sure the opencl:auto would also work). Thank you for the reply. On a side note I was doing dinner independent study on opencl in college when it first came out, glad to see people using it.
