### ISSUE TITLE
Gridseed USB driver issue

### ISSUE THREAD

**Issue by SalvorinFex** [luke-jr/bfgminer#618]
I have looked for the right USB drivers to work with the Gridseed 3355 but I can't seem to get one to work for bfgminer.  The miner is on COM4 and I have tried autoscan via the command line and adding it with the M+ but neither work.

Thank you

Sal

**Comment by SalvorinFex** [comment]
I would like to get these miners up and running, Do you have any advice for me on this issue?

**Comment by nwoolls** [comment]
What drivers did you install and on what OS? The GridSeed ASICs require a custom CDC driver on Windows. You can review a list of ASICs and their drivers (with downloads) here:

https://github.com/nwoolls/MultiMiner/wiki/Drivers

After the proper drivers are installed, the following command should list your ASICs:

`bfgminer -d? -S noauto -S gridseed:all --scrypt`

**Comment by SalvorinFex** [comment]
I am running Windows 10 but just for testing, probably either ending up on Winodws 7 or Server 2008  Also, I wanted to mine BTC not Scrypt, even though I know that is not recommended.
What does the -d do for bfgminer?

**Comment by nwoolls** [comment]
Mining SHA256 is not supported with the current GridSeed code in BFGMiner.

Either way you will need to install the driver linked above for Windows, including jumping through any hoops for installing an unsigned INF.

**Comment by SalvorinFex** [comment]
OHH, that might be part of my problem then.

**Comment by SalvorinFex** [comment]
This issue may be closed, Thanks.
