### ISSUE TITLE
autogen.sh error on Solaris 10 sparc

### ISSUE THREAD

**Issue by baconpantsuppercut** [luke-jr/bfgminer#623]
Running autoreconf -if...
configure.ac:94: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:224: error: possibly undefined macro: AC_MSG_CHECKING
configure.ac:227: error: possibly undefined macro: AC_MSG_RESULT
configure.ac:228: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:333: error: possibly undefined macro: AC_CHECK_DECL
configure.ac:411: error: possibly undefined macro: AC_MSG_WARN
configure.ac:485: error: possibly undefined macro: AC_TRY_LINK
configure.ac:708: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:1208: error: possibly undefined macro: AC_MSG_NOTICE
autoreconf: /opt/csw/bin/autoconf failed with exit status: 1
Updating version.h...
Undefined label: ;d

**Comment by luke-jr** [comment]
Sounds like autoconf is obsolete/broken. And sed too..
