### ISSUE TITLE
autogen.sh error on Raspberry PI 2

### ISSUE THREAD

**Issue by ilma1** [luke-jr/bfgminer#627]
Hi,

When installing I get this:
Configure.ac :35: warning: macro  AM_PATH_LIBGCRYPT not found in library
Configure.ac :29: warning: AM_PATH_LIBGCRYPT missing; CLI tool will not be available

And there is no make file.

Best regards
Magnus

**Comment by luke-jr** [comment]
Read README.

**Comment by WangleX** [comment]
1.Try : 
"apt-get remove autogen automake autoconf libtool m4"
2. Type ''whereis xxx"(xxx is one of autogen automake autoconf libtool m4)
to find out where these file are still, then delete them all !
3.Type
"apt-get install autogen automake autoconf libtool m4"
to reinstall these packages
I've got the same errors as yours, then fixed them via this method. You can try it out! 
My platform is raspian on raspberry pi

**Comment by monkins1010** [comment]
whats the fix for this if you have mingw?  and trying to compile bfgminer. 
how do i install libgcrypt20 on mingw?  thanks kindly
