### ISSUE TITLE
What are the parameters affecting all-time average hash rate (effective)?

### ISSUE THREAD

**Issue by anto** [luke-jr/bfgminer#631]
Hi Luke,

In the attempts to have both of my Antminer U3' continuously running, I played around with the voltage, clock and timing parameters. I think I have an idea on how to control the all-time average hash rate (let's name it A figure). But I still cannot figure out how to control the all-time average effective hash rate (let's name this one B figure).

I initially thought that the A figure is always higher than the B figure, as the B figure is the adjusted A figure based on the actual nonces found and the accepted shares by the pool. But that does not seem to be the case as the B figure seems to remain at a certain hash rate, in my case it is 50 GH/s per miner. And at a certain combination of voltage, clock and timing parameters that are theoretically not possible to reach 50 GH/s, the A figure becomes less than the B figure.

For an understandable reason, BFGMiner is using the B figure in its communication with the pool (in my case Eligius mining pool). But that makes the A figure irrelevant. And the voltage, clock and timing parameters have no or little affect on the B figure. Please have a look below on some screenshots which I hope explain my confusion.

Could you please explain in detail what are the parameters affecting the B figure, so that we can have better control over it to slow down the hashing to have stable miner? 

Cheers,

Anto

Hash rates with voltage=x775, clock=x0782 (200 MHz) and timing=0.0100 - A figure > B figure
![1st figure](https://minifora.eu/public/bfgminer/bfgminer_voltage_x775_-_clock_x0782_-_timing_0.0100.png)

Hash rates with voltage=x775, clock=x0882 (225 MHz) and timing=0.0158 - A figure > B figure
![2nd figure](https://minifora.eu/public/bfgminer/bfgminer_voltage_x775_-_clock_x0882_-_timing_0.0158.png)

Hash rates with voltage=x750, clock=x0782 (200 MHz) and timing=0.0175 - A figure is close to B figure - running only for 1 hour 37 minutes
![3rd figure](https://minifora.eu/public/bfgminer/bfgminer_voltage_x750_-_clock_x0782_-_timing_0.0175.png)

Hash rates with voltage=x750, clock=x0782 (200 MHz) and timing=0.0175  - A figure is close to B figure - 1st miner (AMU 0) crashed in about 10 hours
![4th figure](https://minifora.eu/public/bfgminer/bfgminer_voltage_x750_-_clock_x0782_-_timing_0.0175_1st_miner_crashed.png)

Hash rates with voltage=x750, clock=x0D83 (175 MHz) and timing=0.0212 - A figure < B figure
![5th figure](https://minifora.eu/public/bfgminer/bfgminer_voltage_x750_-_clock_x0D83_-_timing_0.0212.png)

**Comment by luke-jr** [comment]
Probably clock is the only one of relevance.
