### ISSUE TITLE
BFGMiner 5.4.0 dies on startup with Antminer U2

### ISSUE THREAD

**Issue by chazzTSC** [luke-jr/bfgminer#643]
Was running 5.2.0-2 (special build created from 5.2.0 some months ago because of this same problem -- U2 dying at startup). Replaced with 5.4.0 and now crashes on startup again.

Command line bfgminer.exe --no-submit-stale --set-device antminer:clock=x0981 -o stratum+tcp://mint.bitminter.com:3333 -u chazz_antminer1 -p AnythingGoesHere -S amu:all - D -T --verbose

Log file attached

[bfgminer-log.txt](https://github.com/luke-jr/bfgminer/files/34364/bfgminer-log.txt)

**Comment by luke-jr** [comment]
Where did your 5.2.0-2 come from?

**Comment by chazzTSC** [comment]
You sent it to me yourself, on 9 July 2015. Issue #621 (?)

**Comment by luke-jr** [comment]
#621 was about a hang, not a crash?

**Comment by chazzTSC** [comment]
Ah. Yes, so it was. This one is a crash, even pops up the Windows 
"BFGMiner has stopped working" prompt. Windows 7 x64, 64-bit version of 
BFGMiner.

There was a second one, 5.2.0-2 crashes at startup when pool not found 
(626), but that was closed as no rep because I couldn't reliably 
replicate it, and seemed to stop being a problem when I switched to 
explicitly include stratum on the command line.

Probably I was conflating the two of them.

**Comment by luke-jr** [comment]
Well, I'll need a backtrace of some sort to get anywhere on this... :/

**Comment by chazzTSC** [comment]
Of course. Waiting for marching orders...

**Comment by chazzTSC** [comment]
For what it's worth the antminer is coming up as com16.

**Comment by luke-jr** [comment]
I don't know how to get a backtrace on Windows if it doesn't print it on the command prompt automatically.

**Comment by chazzTSC** [comment]
While I can trigger the debugger on failure, I don't have a symbol file 
that I can use to make the resulting stack trace of any use. When you 
built the 64-bit Windows executable, it will have produced a .pdb file. 
Is there some place I can get that file?

**Comment by luke-jr** [comment]
No, I don't think there is any way to produce a .pdb file with MingW. The official Windows binaries are all built with GDB-compatible debugging information in the EXEs/DLLs themselves.

**Comment by luke-jr** [comment]
https://github.com/rainers/cv2pdb may work.

**Comment by chazzTSC** [comment]
I'll take a look at that tomorrow; it's possible that one of the 
debuggers I have access to on that machine may be able to parse that.

**Comment by dthorpe** [comment]
Similar error at startup with bfgminer 5.4.0 on Win7 32 bit:

[error.log.txt](https://github.com/luke-jr/bfgminer/files/35924/error.log.txt)

bfgminer 5.1.0 has no issue with the antminer USB asics. 

Tail: 

```
Failed to init bfd from (C:\Windows\system32\msvcrt.dll)
0x76b0de70 : C:\Windows\system32\msvcrt.dll : strstr 
0x48acfe : C:\Users\Owner\Documents\bfgminer-5.4.0-win32\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-5.4.0-tmp/bfgminer-5.4.0/driver-antminer.c (76) : in function (antminer_detect_one_with_drv) 
0x48add4 : C:\Users\Owner\Documents\bfgminer-5.4.0-win32\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-5.4.0-tmp/bfgminer-5.4.0/driver-antminer.c (95) : in function (antminer_detect_one) 
0x471ce9 : C:\Users\Owner\Documents\bfgminer-5.4.0-win32\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-5.4.0-tmp/bfgminer-5.4.0/lowl-vcom.c (811) : in function (vcom_lowl_probe_wrapper) 
0x48ae37 : C:\Users\Owner\Documents\bfgminer-5.4.0-win32\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-5.4.0-tmp/bfgminer-5.4.0/driver-antminer.c (107) : in function (antminer_lowl_probe) 
0x42de32 : C:\Users\Owner\Documents\bfgminer-5.4.0-win32\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-5.4.0-tmp/bfgminer-5.4.0/miner.c (12633) : in function (_probe_device_do_probe) 
0x42e4c6 : C:\Users\Owner\Documents\bfgminer-5.4.0-win32\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-5.4.0-tmp/bfgminer-5.4.0/miner.c (12786) : in function (probe_device_thread) 
Failed to init bfd from (C:\Users\Owner\Documents\bfgminer-5.4.0-win32\pthreadGC2.dll)
0x6248671b : C:\Users\Owner\Documents\bfgminer-5.4.0-win32\pthreadGC2.dll : pthread_create 
Failed to init bfd from (C:\Windows\system32\msvcrt.dll)
0x76b11287 : C:\Windows\system32\msvcrt.dll : itow_s 
Failed to init bfd from (C:\Windows\system32\msvcrt.dll)
0x76b11328 : C:\Windows\system32\msvcrt.dll : endthreadex 
Failed to init bfd from (C:\Windows\system32\kernel32.dll)
0x77c7ee6c : C:\Windows\system32\kernel32.dll : BaseThreadInitThunk 
Failed to init bfd from (C:\Windows\SYSTEM32\ntdll.dll)
0x77b23ab3 : C:\Windows\SYSTEM32\ntdll.dll : RtlInitializeExceptionChain 
Failed to init bfd from (C:\Windows\SYSTEM32\ntdll.dll)
0x77b23a86 : C:\Windows\SYSTEM32\ntdll.dll : RtlInitializeExceptionChain 
```

command line: 

```
bfgminer -o http://localhost:18332 -u [uname] -p [pwd] -S all --debuglog --debug -T 2>error.log
```

**Comment by chazzTSC** [comment]
My debugger doesn't seem to have picked up symbols, and as yet I have 
not been able to access my work desktop to build either gdb or the PDB 
conversion tool (both seem to be available only as source), but what I 
can see seems to match this back trace. I believe these are the same 
problem.

**Comment by luke-jr** [comment]
Please both of you test http://luke.dashjr.org/tmp/code/webisect/webisect.php?dobuild=bfgminer to see if your problems are fixed.

**Comment by chazzTSC** [comment]
Selected version 5.4.0-5-g7a98c1 seems to work properly on Windows 64 
with the Antminer U2.

**Comment by dthorpe** [comment]
Build 5.4.0-5-g7a98c1 runs fine on Win7 32 bit.

Thanks!
