### ISSUE TITLE
ltcurls.conf used but bfgurls.conf created

### ISSUE THREAD

**Issue by redskate** [luke-jr/bfgminer#648]
Hi, I am using the mac version with an iMac with Yosemite.

The app is trying to access /Users/<user>/Library/Application Support/MacMiner/ltcurls.conf but there was no such ltcurls.conf under the directory. Just another file bfgurls.conf ... 

Workaround: Setup a symbolic link.
Maybe you can fix it in the next release.

Thanks a lot

**Comment by luke-jr** [comment]
Looks like a MacMiner issue, not BFGMiner.

**Comment by redskate** [comment]
The generating issue was a Pool password containing a @. Eliminating this @ from the password “solved” the problem.

-- 
GMAIL
Sent with Airmail

On 15 December 2015 at 23:56:29, Luke-Jr (notifications@github.com) wrote:

Looks like a MacMiner issue, not BFGMiner.
