### ISSUE TITLE
The inquiry of errror message from BFGMienr.

### ISSUE THREAD

**Issue by jeong760** [luke-jr/bfgminer#658]
Dears,

I've recevied an following message on BFGminer but I am not sure this is related with BFGminer 
however I want know the reason why following errors occurred.
- I use a Eloipool as solo mining pool fo bitcoin
- miner is connect to Eloipool using BFGMiner 
- Error message are
  - "Method 'mining.suggest_target' not found", null
  - Message from pool 0: This stratum server is licensed under the GNU Affero General Public 
    License, version 3. You may download source code over stratum using the server.get_source
    method.

Regards,
John Ahn

**Comment by luke-jr** [comment]
> "Method 'mining.suggest_target' not found", null

That looks like a mere warning?

> Message from pool 0: This stratum server is licensed under the GNU Affero General Public License, version 3. You may download source code over stratum using the server.get_source method.

Copyright disclosure. Not an error.

**Comment by jeong760** [comment]
How I can check for Eloipool and BFGMiner working well together?
