### ISSUE TITLE
Can not set up config

### ISSUE THREAD

**Issue by RepoBike** [luke-jr/bfgminer#659]
Trying to config before installing for cpu mining LTC. Or atleast trying to. So far nothing has been working.

Linux Mint 17.2

This is the 6th guide iv found and this is the 6th time it has failed to install. 
Might need a way better install guide. 
Installing from the software MGR works but nothing enabled and unable to edit the settings.

any other options out there that will work?

**Comment by luke-jr** [comment]
Altcoins are not officially supported.

**Comment by RepoBike** [comment]
Thank you for the reply.

Whats a good miner for LTC?

**Comment by luke-jr** [comment]
I also personally don't support [scams like Litecoin](https://bitcointalk.org/index.php?topic=23768.msg3815348#msg3815348).
