### ISSUE TITLE
raw tcpip socket driver - help 

### ISSUE THREAD

**Issue by mahalamobile** [luke-jr/bfgminer#664]
Hi all,

Im trying to make a driver for a raw tcp ip connection to send work and then received a found nounce back based on a set difficulity. Im not a c or c++ developer i must admit so please bear with me. I based the driver code on gridseed as this seemed to be the easiest and also what i could understand. My question is, how can i embed my driver and helper functions to be able to build with --enable-mytcpdriver as a parameter? What is the best way to test this? As i have a tcp server that simply for now echos back what work it "should" receive" on the socket. Where can i paste and or send me code for some community help? this would be great :) and really appreciated

/*
- bm500.c
  *
-  Created on: 13 Jun 2016
-      Author: User
  */
# include "config.h"
# include "bm500.h"
# include "miner.h"
# include "logging.h"
# include <stdint.h>
# include <string.h>
# include <stdio.h>
# include <stdlib.h>
# include <unistd.h>
# include <errno.h>
# include <netdb.h>
# include <sys/types.h>
# include <netinet/in.h>
# include <sys/socket.h>
# define SPORT                    3490
# define RPORT                    3491
# define MAXDATASIZE              256
# define BUURMAN_CHIP_NAME        "buurman"
# define BUURMAN_COMMAND_DELAY_MS  20
# define BUURMAN_WRITE_DELAY_MS    10

struct sockaddr_in server_info;
struct hostent _he;
int socket_fd,num;
char buffer[1024];
char buff[1024];
unsigned char bytes[4];
char_ ipbuff = malloc(10);

static
int bm500_open(const char *ip)
{
    int i = 0;

```
ipbuff = strtok(ip,".");
while (ipbuff != NULL)
{
   bytes[i] = (unsigned char)atoi(ipbuff);
   ipbuff = strtok(NULL,".");
   i++;
}

if ((he = gethostbyname(ip))==NULL) {
    return -1;
}

if ((socket_fd = socket(AF_INET, SOCK_STREAM, 0))== -1) {
    return -1;
}

memset(&server_info, 0, sizeof(server_info));
server_info.sin_family = AF_INET;
server_info.sin_port = htons(PORT);
server_info.sin_addr = *((struct in_addr *)he->h_addr);
if (connect(socket_fd, (struct sockaddr *)&server_info, sizeof(struct sockaddr))<0) {
    return -1;
}

return atoi(ipbuff);
```

}

static
void buurman_log_protocol(int fd, const char *buf, size_t size, const char *prefix)
{
    char hex[(size \* 2) + 1];
    bin2hex(hex, buf, size);
    applog(LOG_DEBUG, "%s fd=%d: DEVPROTO: %s(%3lu) %s",
            BUURMAN_CHIP_NAME, fd, prefix, (unsigned long)size, hex);
}

ssize_t buurman_read(int fd, char *buf, size_t size)
{
    //size_t read = serial_read(fd, buf, size);
    num = recv(socket_fd, buffer, sizeof(buffer),0);
    if (num > 0 ){
        buf[num] = '\0';
    }
    if ((num > 0) && opt_dev_protocol)
        buurman_log_protocol(fd, buf, read, "RECV");

```
return sizeof(buf);
```

}

ssize_t buurman_write(int fd, const void \* const buf, const size_t size)
{
    if (opt_dev_protocol)
        buurman_log_protocol(fd, buf, size, "SEND");

```
//ssize_t result = write(fd, buf, size);
if ((send(socket_fd,buf, strlen(buf),0))== -1) {}

cgsleep_ms(BUURMAN_WRITE_DELAY_MS);

return sizeof(buf);
```

}

void buurman_init_miner(int fd)
{

}

void buurman_close(int fd)
{
    free(ipbuff);
    close(socket_fd);
}

void bm500_scrypt_prepare_work(unsigned char cmd[156], struct work *work)
{

```
// command header
cmd[0] = 0x55;  // static header
cmd[1] = 0x00;  // static header
cmd[2] = 0x00;  // (for Scrypt)
cmd[3] = 0x00;  // identifier

// task data - starts at 0x0 (with 4 byte offset for header)
memcpy(cmd + 4, work->target, 32);
memcpy(cmd + 36, work->midstate, 32);
memcpy(cmd + 68, work->data, 80);

// nonce min - starts at 0x23 (with 4 byte offset for header)
cmd[144] = 0x00;
cmd[145] = 0x00;
cmd[146] = 0x00;
cmd[147] = 0x00;

// nonce max - starts at 0x24 (with 4 byte offset for header)
cmd[148] = 0xff;
cmd[149] = 0xff;
cmd[150] = 0xff;
cmd[151] = 0xff;

// 0x25 - 0x28 are for specific Scrypt unit configs, don't set without reason
```

}

**Comment by luke-jr** [comment]
Replied via email
