### ISSUE TITLE
bfgminer crashes when adding a device.

### ISSUE THREAD

**Issue by wzsanders** [luke-jr/bfgminer#669]
bfgminer version 5.4.2-unknown
Installed with brew tap nwoolls/xgminer
then brew install --HEAD bfgminer

using the command bfgminer -o http://mint.bitminter.com:3333 -u username -p password -I d
this brings up the main interface and I am prompted to add a device.
pressing m and + then prompts my to type _all, auto or a serial port_ 
upon entering auto, the command line outputs this:

[1] 49468 trace trap [the command I used earlier]

**Comment by luke-jr** [comment]
Can you get a backtrace, or at least a debug log?

**Comment by wzsanders** [comment]
Kind of new to the debug thing, but I think I did this right?

https://gist.github.com/wsanders99/3c25c103601d0958c2ac76197f1d6802

The files that aren't being found seem to be because the card I'm using not being a standard graphics card. The machine has a GTX 970 with custom drivers from [here](http://us.download.nvidia.com/Mac/Quadro_Certified/346.02.03f02/WebDriver-346.02.03f02.pkg).

**Comment by luke-jr** [comment]
Sounds like buggy GPU drivers. Maybe try adding the specific device(s) you want explicitly, so you don't add GPUs?
