### ISSUE TITLE
Solo Mining Bitcoin 0.12.1 - blktmpl error: Unrecognized block version

### ISSUE THREAD

**Issue by Aragonite** [luke-jr/bfgminer#670]
Ubuntu 16.04 LTS, Bitcoin-core 0.12.1. bfgminer 5.4.2

Getting the subject error with above configuration.  

Also, will not connect to the internal node.

**Comment by luke-jr** [comment]
Core 0.12.1's GBT is broken. You will need to switch to Knots or manually patch Core.

See https://bitcointalk.org/index.php?topic=877081.msg15437532#msg15437532 for more info.
