### ISSUE TITLE
Can't "make" the file...

### ISSUE THREAD

**Issue by pfmd86** [luke-jr/bfgminer#679]
Hi,

I just cloned the git to my Raspi3. After that I "./autogen.sh" and "./configure"
But the make doesn't work.
The result is:

> make: **\* No targets specified and no makefile found. Stop.
> I still googled for that message. All i found was that the makefile shouldn't have an file extension but it has .am an .in

What am I doing wrong?

**Comment by luke-jr** [comment]
Presumably you didn't install the required dependencies, and either autogen.sh and/or configure failed.
