### ISSUE TITLE
cant get this to work on raspie 3b

### ISSUE THREAD

**Issue by j0nnay-aw83n** [luke-jr/bfgminer#688]
okay so i can do these steps
git clone https://github.com/luke-jr/bfgminer.git
cd bfgminer
./autogen.sh
./configure
but once i run the make command it says there is no such command. please help ive been at this all day. i have found no helpful info,

**Comment by luke-jr** [comment]
See `README`

**Comment by j0nnay-aw83n** [comment]
okay i have read it, now still! i can not get the make command to work, i can not get a pool open since i can not finish the setup process, please explain why i would be having this error.

**Comment by j0nnay-aw83n** [comment]
okay so if you're having this problem download the file then overwrite what was added from the apt.get this fixed my problem.
