### ISSUE TITLE
NO DEVICES FOUND

### ISSUE THREAD

**Issue by hiker3954** [luke-jr/bfgminer#690]
Hi,

I run the program and it works, entered pool details, login, pass and then it says:

NO DEVICES FOUND

I don't know how to install them, neither "all" and "auto" worked...

Thanks in advance.
![bfgminer](https://cloud.githubusercontent.com/assets/26688501/24331024/14805350-122c-11e7-80e3-36c6c5c13432.png)

**Comment by luke-jr** [comment]
If they're USB, plug them in a USB port... At least be specific about what miner you're trying to use.

**Comment by luke-jr** [comment]
And read `README.ASIC` first

**Comment by hiker3954** [comment]
I use my PC for the moment, no ASIC miner machine...
