### ISSUE TITLE
[QUESTION] Cross-building

### ISSUE THREAD

**Issue by Tutul-** [luke-jr/bfgminer#695]
Hi there, I just wondering if it's possible to cross-compile it from Linux to run on Windows (10 x86_64) ?
I don't have enought space on my windows to setup the build environment.

I want to compile it to include CPU support, I know, it's not verry efficient but it's only for testing purpose :)

**Comment by luke-jr** [comment]
Yes, it is possible. Official builds are made this way.

**Comment by fogoat** [comment]
Can you provide a resource for compiling bfgminer under Windows 10 64-bit using Windows Subsystem for Linux (WSL) -> Ubuntu 16.0.4 LTS ?

I tried using some instructions from here:
https://github.com/HTMLCOIN/HTMLCOIN/issues/15

bfgminer compiles okay and runs fine as a Linux binary, but I can't seem to create an EXE for Windows
