### ISSUE TITLE
Why 2 pools active?

### ISSUE THREAD

**Issue by mutluit** [luke-jr/bfgminer#702]
Hi,
using GBT (no stratum, no longpoll) to local server, bfgminer creates 2 pools:
"
0: Enabled   GBT  Quota 1 Pool 0: http://localhost:8332  User:xxx
1: Enabled   GBT  Quota 0 Pool 1: http://localhost:8332/#allblocks  User:xxx

Current pool management strategy: Failover
"

Why is that so? Shouldn't there be just 1 pool?

And this one:
[2017-06-28 04:40:42] Local bitcoin RPC server on port 8332 found in /home/xxx/.bitcoin/bitcoin.conf

Why the need for accessing/reading the config file of the server?

**Comment by luke-jr** [comment]
BFGMiner automatically adds a local bitcoind as a final fallback.

**Comment by luke-jr** [comment]
See `--no-local-bitcoind` if you want to disable it.

**Comment by mutluit** [comment]
Thx, that worked. But the switch is --no-local-bitcoin (without the d at the end)
