### ISSUE TITLE
Downloads linking to malicious site

### ISSUE THREAD

**Issue by WebDeveloperAndrew** [luke-jr/bfgminer#707]
All the download links I've tried to follow lead to a malicious site that is not affiliated with the author, how can I get a working copy of bfgminer?

**Comment by mutluit** [comment]
Take a look at the authors site:
http://bfgminer.org/files/latest/

Or, compile it yourself from the source code.

**Comment by madhatr** [comment]
I downloaded the latest 5.5x and Windows Defended set off a trojan alarm.   I imagine it is false alarm, just wondering why.   
Trojan:Win32/Tilken.B!cl

Edit, this was from http://bfgminer.org/files/latest/  win64 version

**Comment by luke-jr** [comment]
Because anti-virus authors are incompetent bigots who consider Bitcoin mining to be fundamentally malware.

**Comment by Leadwerks** [comment]
That website says "This site is not affiliated with BFGMiner and is not the official page of the software."?
