### ISSUE TITLE
NVIDIA GeForce GTX 1050 (Notebook) not recognized by BFGMiner

### ISSUE THREAD

**Issue by Zurkan660** [luke-jr/bfgminer#712]
I use slush's pool and I have "start cmd /k bfgminer -S opencl:auto" in a batch file that is in the BFGMiner folder. It detect one device, but my graphic card (GTX 1050) is not affected...

It just shows that:

 bfgminer version 4.10.6 - Started: [2017-08-18 17:05:36] - [  0 days 01:15:13]
 [M]anage devices [P]ool management [S]ettings [D]isplay options                                            [H]elp [Q]uit
 Pool 0: ...m.slushpool.com  Diff:128  +Strtm  LU:[17:20:30]  User:Dont want to show that
 Block: ...89862505 #481150  Diff:923G ( 6.61Eh?)  Started: [17:15:30]
 ST:4  F:0  NB:4  AS:0  BW:[ 49/  3 B/s]  E:0.00  I: 0.00 BTC/hr  BS:1
 1            |  7.75/ 7.62/ 9.54Mh/s | A:0 R:0+0(none) HW:0/none
--------------------------------------------------------------------------------------------------------------------
 OCL 0:       |  7.75/ 7.62/14.12Mh/s | A:0 R:0+0(none) HW:0/none
--------------------------------------------------------------------------------------------------------------------
Logs
--------------------------------------------------------------------------------------------------------------------

**Comment by luke-jr** [comment]
OCL is a graphics card.
