### ISSUE TITLE
/dev/mem trouble: Permission denied

### ISSUE THREAD

**Issue by tonylambiris** [luke-jr/bfgminer#713]
Can you provide any specifics as to what/why it needs access to `/dev/mem`?

My workstation has read access but still says it can't access it?
```
╭─ 17:16:31  ~                                                                                            11.87   c1-linuxdev 
╰ ls -la /dev/mem
crw-r----- 1 root kmem 1, 1 Sep  3 18:01 /dev/mem
╭─ 17:16:34  ~                                                                                                     c1-linuxdev 
╰ id
uid=1000(tlambiris) gid=9(kmem) groups=9(kmem),10(wheel),56(bumblebee),78(kvm),90(network),91(video),92(audio),93(optical),94(floppy),95(storage),96(scanner),97(input),98(power),100(users),108(vboxusers),150(wireshark),618(libvirt),619(plugdev),994(docker),1000(vmware)
```

![screenshot-20170905171448-1227x709](https://user-images.githubusercontent.com/14058972/30083964-81c5f3cc-925e-11e7-8fea-6d3df2102b97.png)

Thanks for the software, other than the above everything else works great!

**Comment by luke-jr** [comment]
SPI devices use it, and need r/w access. But none of them are enabled by default...
