### ISSUE TITLE
bfgminer-5.4.2: little/no compilation documentation in .tar.gz, instructions from Github don't work

### ISSUE THREAD

**Issue by dchmelik** [luke-jr/bfgminer#714]
The bfgminer-5.4.2.tar.gz seems to have no documentation how to compile, so I checked the bfgminer project page here on Github.  It says for GNU/Linux I only need to run configure if I didn't get  the .tar.gz from .git (the case, as I typed '.autogen.sh,' which complained about .git stuff not existing.)  However... there just isn't a 'configure' file in the .tar.gz, only 'configure.ac.'  Please add some correct documentation (preferably in each source code archive file) or the files current documentation refers to (configure.)

**Comment by luke-jr** [comment]
No idea what `bfgminer-bfgminer-5.4.2.tar.gz` is, but README is part of all official BFGMiner distributions.
