### ISSUE TITLE
bfgminer-5.4.2: no 'configure' file

### ISSUE THREAD

**Issue by dchmelik** [luke-jr/bfgminer#715]
The [bfgminer-5.4.2.tar.gz](https://github.com/luke-jr/bfgminer/archive/bfgminer-5.4.2.tar.gz) file (which gets saved as bfgminer-bfgminer-5.4.2.tar.gz, which you could have checked in relation to issue #714, has no 'configure' file. Please add some correct documentation (preferably in each source code archive file, maybe above usage instructions, if the archive file doesn't have a binary executable file anyway) or the files current documentation refers to (configure.)

**Comment by luke-jr** [comment]
Spamming will not help you. The documentation is correct. Your link is wrong.

**Comment by dchmelik** [comment]
So, this isn't your project https://github.com/luke-jr/bfgminer/archive/bfgminer-5.4.2.tar.gz ?  That's what my link above was.  It appears either you didn't see that's in a sub-directory of this project (that I'm posting this as an issue on its page) or you're the spammer/troll.
