### ISSUE TITLE
Cflags:: Invalid argument. bfgminer-2.10.12. MinGW.

### ISSUE THREAD

**Issue by openGLnoob** [luke-jr/bfgminer#742]
Hi Luke! I'm trying to build an old bfgminer just with GBT and OpenCL support, but w/o any addons. I follow windows instruction, but on stage "make" I get this error:

**gcc.exe: error: Cflags:: Invalid argument**

Before that I set CFLAGS to "-O2 -msse2" as required. 

This is the end of log:

  **...
  CC     bfgminer-miner.o
  CC     bfgminer-util.o
  CC     bfgminer-sha2.o
  CC     bfgminer-api.o
  CC     bfgminer-logging.o
  CC     bfgminer-driver-opencl.o
  CC     bfgminer-ocl.o
  CC     bfgminer-findnonce.o
  CC     bfgminer-adl.o
  CC     bfgminer-fpgautils.o
  CC     bfgminer-dynclock.o
  CC     bfgminer-driver-bitforce.o
  CC     bfgminer-driver-icarus.o
  CC     bfgminer-driver-cairnsmore.o
  CC     bfgminer-driver-modminer.o
  CCLD   bfgminer.exe
gcc.exe: error: Cflags:: Invalid argument
make[2]: *** [bfgminer.exe] Error 1
make[2]: Leaving directory `/home/User/bfgminer-bfgminer-2.10.12'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/User/bfgminer-bfgminer-2.10.12'
make: *** [all] Error 2**

**Comment by monkins1010** [comment]
i think its something to do with not dinign the opencl.dll???  We have been able to do this by using the MinGW reimp and dlltool utilities to create an import library "libOpenCL.a" for the "OpenCL.dll" DLL. Here are the steps we followed:

step 1: Make sure you have mingw-utils installed (for reimp and dlltool). If you don't, at a MinGW prompt, type:

mingw-get install mingw-utils
step 2: Next, type the following command:

reimp OpenCL.lib
This should yield an OpenCL.def and libOpenCL.a file. If the result is something along the lines of "invalid or corrupt import library", the alternative step 2 should work.

alternative step 2: Use dlltool together with a .def file that you can find here: http://pastebin.com/f2ac38b2f . The command becomes:

dlltool -l libOpenCL.a -d OpenCL.def -A -k
You can now link against the newly created libOpenCL.a. If you still see missing symbols, add them to the .def file and repeat the dlltool command.

**Comment by luke-jr** [comment]
This is almost certainly user error.

Regardless, old versions are not supported. New ones exist for a reason...
