### ISSUE TITLE
Pool list vs actual pool number - remove numbers on right?

### ISSUE THREAD

**Issue by fogoat** [luke-jr/bfgminer#744]
Using bfgminer 5.4.2 on @jstefanop ML2 compiled macOS binary.

I find it confusing when you two numbers. 

What are the two set of numbers for?

![q7dtexv 1](https://user-images.githubusercontent.com/6989799/35870543-c9b6fdee-0b16-11e8-9892-ccbcb5d06211.png)

**Comment by luke-jr** [comment]
The number on the left is your configured priority for the pool. The number on the right is a pool identification number.
