### ISSUE TITLE
Windows 10 -  V 5.5.0 and 5.5.x does not detect Moonlander

### ISSUE THREAD

**Issue by batusy** [luke-jr/bfgminer#746]
The new version 5.5.0 does not detect Moonlander in Windows 10

Can you help me?

Thank

**Comment by fogoat** [comment]
it recognizes fine for me. did you install the silicon labs vpc drivers?

**Comment by jstefanop** [comment]
You have to use driver in my fork. Moonlander support has not been merged into main branch yet.
