### ISSUE TITLE
cannot find libtinfow library

### ISSUE THREAD

**Issue by coreyhahn** [luke-jr/bfgminer#798]
configure and make all complete normally.  But upon execution in the build directory 

./bfgminer -o http://localhost:8332 -u user -p password

i get the error.

./bfgminer: error while loading shared libraries: libtinfow.so.6: cannot open shared object file: No such file or directory

Edit:
I am on ubuntu 20.04

**Comment by coreyhahn** [comment]
I see i have libtinfo library installed but i see no way to install a libtinfo**w** library.

**Comment by coreyhahn** [comment]
sudo ln -s /lib/x86_64-linux-gnu/libtic.so.6.2 /lib/x86_64-linux-gnu/libtinfow.so.6

fixed me up for now.

**Comment by host452b** [comment]
> sudo ln -s /lib/x86_64-linux-gnu/libtic.so.6.2 /lib/x86_64-linux-gnu/libtinfow.so.6
> 
> fixed me up for now.

that help me , thx
