### ISSUE TITLE
Google is abusively slandering...type in a .org/files/ after the BFGMiner name

### ISSUE THREAD

**Issue by quietpixel** [luke-jr/bfgminer#822]
Clicking the Downloads link in the Readme leads to the following notice:

**Google is abusively slandering my entire website if I link you, so please manually type in a .org/files/ after the BFGMiner name.**

Could you clarify what URL to use when typing in the extra .org/files/?  I have tried:

http://luke.dashjr.org/programs/bitcoin/files/bfgminer.org/files
http://luke.dashjr.org/programs/bitcoin/files/bfgminer/.org/files
http://luke.dashjr.org/programs/bitcoin/files/bfgminer/bfgminer.org/files
http://luke.dashjr.org/bfgminer.org/files/
http://luke.dashjr.org/bfgminer/.org/files/
https://github.com/luke-jr/bfgminer.org/files/

and numerous others, none of which work.

What exact URL is the .org/files/ string supposed to be appended to?

**Comment by duzhaokun123** [comment]
http://luke.dashjr.org/programs/bfgminer/

**Comment by quietpixel** [comment]
Thank you @duzhaokun123
