### ISSUE TITLE
Bfgminer for litecoin

### ISSUE THREAD

**Issue by sachinverma1** [luke-jr/bfgminer#844]
Hi, .

I am trying to mine litecoin solo...  I want to know does bfgminer works for litecoin...

If yes then any article will be helpful for me.

Thank you

**Comment by wareck** [comment]
yes...
enable scrypt during configuration (and you also need hardware support scrypt/litecoin)
I'm using bfgminer since a while for liecoin...

**Comment by sachinverma1** [comment]
Thank you for your response.. How I can enable scrypt in bfgminer while
mining on litecoin...?

**Comment by wareck** [comment]
download bfgminer from source , autogen config files, then configure

sudo apt-get update -y
sudo apt-get install git build-essential autoconf automake libtool pkg-config libcurl4-gnutls-dev \
    libjansson-dev uthash-dev libncursesw5-dev libudev-dev libusb-1.0-0-dev \
    libevent-dev libmicrohttpd-dev libhidapi-dev libgcrypt20-dev -y

git clone https://github.com/luke-jr/bfgminer.git
cd bfgminer
./autogen.sh
./configure --enable-scrypt
make


If you want to use litecoin hardware, you can add your driver like zeusminer:

./configure --enable-scrypt --enable-zeus
make

**Comment by sachinverma1** [comment]
Cool... Can I do it on windows 10?

**Comment by sachinverma1** [comment]
W to enable Nvidia GPU support in bfgminer...

**Comment by luke-jr** [comment]
Scamcoins are not supported

**Comment by sachinverma1** [comment]
Issue solved
