### ISSUE TITLE
Document how to set clocks/memory/vddc of arbitrary GPU without setting clocks of other GPU in config file

### ISSUE THREAD

**Issue by ssateneth** [luke-jr/bfgminer#87]
Document that 0 works as a "default value" in some multi-GPU options

Original report:

Say for example you have 8 GPU's in your system and you want to run your GPU's at default speeds except for the 5th one. As far as I know, there is no way to set the clocks of the 5th GPU with the use of a config file without setting the clocks of the 4 GPU's before it.

Proposed solution: Allow the underscore ( _ ) to skip setting clocks/VDDC/fan/whatever of a GPU if you wish it to not change the current clocks/VDDC/fan/whatever.

before: "gpu-engine" : "725,725,725,725,715"
after: "gpu-engine" : "_, _, _, _, 715"

**Comment by luke-jr** [comment]
What happens if you put zero?

**Comment by luke-jr** [comment]
Added in fa1f03c
