### ISSUE TITLE
Rejecting pools (including those flagged for stale-on-arrival work) do not recover on longpoll when its work does not include any shares

### ISSUE THREAD

**Issue by jddebug** [luke-jr/bfgminer#95]
Longpolls are always worked for "rejecting" pools, and the pool revived if the shares from it are accepted. However, if a longpoll work does not contain any valid shares, the pool is left "rejecting" until a longpoll provides a work that does. This behaviour may be appropriate for pools which are in fact rejecting valid shares, but not for those flagged due to stale-on-arrival work.

**---Original Report---**
**Title:** bfgminer will switch to a different pool but will not switch back again until a long time

This is a new issue that showed up in 2.6.4

I have 7 rigs mining, They are all going through gpumax. From time to time some of them will switch to another pool due to ? and they end up stuck there. GPUMAX will show that they reconnect and then immediately disconnect over and over again. Eventually they stop reconnecting I think but am not sure on that. If I go to the pool area and select that pool it will start using it again. I can also quit bfgminer and when I restart it and it will use my main pool (gpumax) again.

**Comment by luke-jr** [comment]
Applying (as needed) during bisect: 57aa649, 34bdbf3, 06041dd, fa3a25f

$ git bisect start bfgminer-2.6.4 bfgminer-2.5.1
Bisecting: 255 revisions left to test after this (roughly 8 steps)
[362c39166a39d7974f47cb43a8ecb8a5b6d8f017] Import uthash 1.9.6

http://luke.dashjr.org/tmp/code/bfgminer-362c391-57-34-06.exe

**Comment by jddebug** [comment]
http://luke.dashjr.org/tmp/code/bfgminer-362c391-57-34-06.exe will crash in a short period of time on windows 7 and a bit longer but crashes on xp too. This makes it hard to test for the issue.

**Comment by jddebug** [comment]
Ok, watched bfl2 windows xp rig successfully switch to backup pool, mine there for a minute or 2 and then reconnect successfully to gpumax. This indicates that at least sometimes, this build I'm testing can go to backup and then come back to main pool. A short time later it crashed though. :(

**Comment by luke-jr** [comment]
$ git bisect good
Bisecting: 127 revisions left to test after this (roughly 7 steps)
[d790a32ed83d2bcae29f17b6e886402bc4d8801a] Merge branch 'mm_relax_idle' into bfgminer

http://luke.dashjr.org/tmp/code/bfgminer-d790a32-57-34-06.exe

**Comment by luke-jr** [comment]
btw, it's no surprise that these will stumble other bugs that have since been fixed. If it's impossible to test one, there is a "skip" option, but it means testing the whole thing will take longer.

**Comment by jddebug** [comment]
After 13 hours it has not gotten stuck using this build. I have watched it switch back and forth. I say try the next build. Unfortunately, I didn't have logging on so I can't see in the logs that it switched but I did OBSERVE it switch and return one time at least. Took a very long time as it had to deal with the limited threads I think.

**Comment by luke-jr** [comment]
$ git bisect good
Bisecting: 63 revisions left to test after this (roughly 6 steps)
[8cfb0dc7c526279d06ed99ccecc6f881e621c03a] Merge branch 'bf_thrttl_nores' into bfgminer

http://luke.dashjr.org/tmp/code/bfgminer-8cfb0dc-57-34-06-fa.exe

**Comment by jddebug** [comment]
After running for dys and watching backup pool activate a couple times and then return to main pool, I believe that this build does not have the issue we are searching for.

**Comment by luke-jr** [comment]
$ git bisect good
Bisecting: 32 revisions left to test after this (roughly 5 steps)
[08b82ef94b6f2e14bcfeb4269e873b3442646949] Merge branch 'opencl_dynlink' into bfgminer

http://luke.dashjr.org/tmp/code/bfgminer-08b82ef-57-34-06-fa.exe

**Comment by jddebug** [comment]
This version seems good. I have watched it successfully switch to backup pools and then return.

**Comment by luke-jr** [comment]
$ git bisect good
Bisecting: 16 revisions left to test after this (roughly 4 steps)
[a0ed5ce3b8dbaab567db1acf24505719cb12b64d] Merge branch 'rename_thr' into bfgminer

http://luke.dashjr.org/tmp/code/bfgminer-a0ed5ce-34-fa.exe

**Comment by jddebug** [comment]
Ok, this version is exhibiting the issue we are looking for.

**Comment by luke-jr** [comment]
$ git bisect bad
Bisecting: 7 revisions left to test after this (roughly 3 steps)
[3a5a34a3e9f8797018d0918e0db89bb1f9798947] Merge branch 'refactor_stale' into bfgminer

http://luke.dashjr.org/tmp/code/bfgminer-3a5a34a-57-34-06-fa.exe

**Comment by luke-jr** [comment]
I'm pretty certain this will come down to one of these (most likely first): 2c1cd8d, d19879e, or 91fdbfa

**Comment by luke-jr** [comment]
Slight change of plan: let's eliminate one of the more likely causes.

Test: http://luke.dashjr.org/tmp/code/bfgminer-f6c2234-57-34-06-fa.exe

**Comment by jddebug** [comment]
Ok, the problem still exists. This build does not like to find my devices very well either.

**Comment by jddebug** [comment]
hmmm, well, some of them have returned to pool 0. It took a VERY long time up until then they were all behaving like the issue we had before but 3 out of 6 did return as of now.

**Comment by jddebug** [comment]
crap, all but one have returned. I think I may need to try the release version again and see if it eventually returns after a LONG period of time. I can say the this is NOT behaving the way it should.

**Comment by luke-jr** [comment]
I presume these last comments were all with f6c2234? Did you manage to get a debuglog from them?

**Comment by jddebug** [comment]
Yes, f6c2234 and No to the debuglog, at least in the previous versions if I had that setting in the config the miner would crash because it was not implemented yet you said.

Also, eventually they have all come back to pool 0. Luke, I may have to test out the release to see if they leave and EVENTUALLY return. Its not behaving the way earlier versions did though. It leaves and tried to return but can't or is very picky about the circumstances that it will chose to return with.

Additionally as I stated above, I was getting complaints from the miner about heat issues and "sick" units and usb issues that I was not in the earlier builds I was testing. Maybe coincidence but was seeing it on almost every rig.

**Comment by jddebug** [comment]
Luke-jr, I thought only the newest version of bfgminer had --debuglog

**Comment by luke-jr** [comment]
All the recent test builds have been recent enough to have it, I think.

**Comment by luke-jr** [comment]
@jddebug reports that the original bug does _eventually_ return also, confirming f6c2234 is bad.

$ git bisect bad f6c2234
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[0f0a3bb07cfaa177c2388352aad9a0877f804873] Merge branch 'bugfix_msg_workstale' into bfgminer

http://luke.dashjr.org/tmp/code/bfgminer-0f0a3bb-57-34-06-fa.exe

**Comment by luke-jr** [comment]
**Identified Cause:** primary pool is "rejecting"-disabled due to providing stale-on-arrival work (other pool longpolled with new block first). "Rejecting" disabled pools are only revived when they start accepting shares, and until they do, are only tested with longpoll work. If the longpoll work doesn't have any valid shares in it, the pool is left "rejecting".

**Comment by luke-jr** [comment]
Please test: http://luke.dashjr.org/tmp/code/bfgminer-93d7378.exe

**Comment by luke-jr** [comment]
The stale-on-arrival failsafe seems to just be a source of problems, and should never be needed in theory. Removed in ebef3d3, which should resolve this.
