### ISSUE TITLE
threads which are retrying shouldn't hold up new submissions

### ISSUE THREAD

**Issue by jddebug** [luke-jr/bfgminer#97]
When switching to backup pool after com errors, bfgminer caches a lot of shares and then tries to submit them but since we have threads limited to avoid the thread crashes it takes forever.

**Comment by luke-jr** [comment]
This looks like it will probably require significant refactoring, to the point that I'm better off rewriting it async. Unfortunately, that will need to wait until 2.7.1.

**Comment by luke-jr** [comment]
Workaround in 78b2a47c0c8c1b7238434b20e18d9209dea3c5f0 and d42ebcfb8b52e6bfc704d836fb55e9bcd20016c2

**Comment by luke-jr** [comment]
Should be fixed in 2.10.0
